---
# binary sensors

- platform: workday
  country: !secret workday_country
  province: !secret workday_province
- platform: ping
  host: !secret rpi_ip
  name: Raspberry Pi
  count: 5
  scan_interval: 60
- platform: meteoalarm
  country: !secret meteo_country
  province: !secret meteo_province
