---
# covers

- platform: group
  name: living_room_group
  entities:
    - cover.fyrtur_1
    - cover.fyrtur_2

- platform: group
  name: bed_room_group
  entities:
    - cover.ikea_of_sweden_fyrtur_block_out_roller_blind_cover_1
    - cover.ikea_of_sweden_fyrtur_block_out_roller_blind_cover_2
