---

entities:
  - sensor.sonoff_3028_version
  - sensor.sonoff_maddox_version
  - sensor.ipad_battery_state
  - sensor.hass_version
  - sensor.ssl_cert_expiry
  - sensor.wakeup_start_time_lights
  - sensor.wakeup_alarm_time
  - sensor.wakeup_fadein_duration
  - sensor.robovac_battery
  - sensor.robovac_status
  - sensor.robovac_fanspeed
