---
# history includes

domains:
  - media_player
  - device_tracker
  - person
  - cover
entities:
  - binary_sensor.presence_10
  - light.zimmer
  - light.buro
  - light.wohnzimmer
  - switch.wind_machine
  - sensor.cpu_temperature
  - sensor.processor_use
  - sensor.disk_free
  - sensor.disk_use_percent
  - sensor.disk_use_percent_lv0
  - sensor.disk_use_percent_lv1
  - sensor.disk_use_percent_sda1
  - sensor.disk_use_percent_sda2
  - sensor.memory_free
  - sensor.memory_use_percent
  - sensor.database_size
  - sensor.exchange_rate_1_btc
  - sensor.google_travel_time_dev1_dynamic_home
  - sensor.google_travel_time_dev1_transit
  - sensor.received_eth0
  - sensor.sonoff_office_temperature
  - sensor.sonoff_office_humidity
  - sensor.wemosd1_room_temperature
  - sensor.wemosd1_room_humidity
  - sensor.sonoff_rssi
  - sensor.sonoff_uptime
  - sensor.sonoff_vcc
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - sensor.speedtest_ping
  - sensor.sent_eth0
  - sensor.stats_ratio_athome
  - sensor.trade_volume
  - sensor.uberx_price
  - sensor.uberx_time
  - sensor.asuswrt_download
  - sensor.asuswrt_upload
  - vacuum.roborock
