---
# history includes

domains:
  - media_player
  - device_tracker
  - person
  - cover
  - climate
entities:
  - binary_sensor.bed_occupancy
  - binary_sensor.motion_sensor
  - binary_sensor.motion_sensor_2
  - light.zimmer
  - light.buro
  - light.living_room
  - switch.wind_machine
  - sensor.bed_pressure_1
  - sensor.bed_pressure_2
  - sensor.cpu_temperature
  - sensor.processor_use
  - sensor.disk_free
  - sensor.disk_use_percent
  - sensor.disk_use_percent_lv0
  - sensor.disk_use_percent_lv1
  - sensor.disk_use_percent_sda1
  - sensor.disk_use_percent_sdb1
  - sensor.disk_use_percent_sdb2
  - sensor.disk_use_percent_sdb3
  - sensor.memory_free
  - sensor.memory_use_percent
  - sensor.database_size
  - sensor.exchange_rate_1_btc
  - sensor.google_travel_time_dev1_dynamic_home
  - sensor.google_travel_time_dev1_transit
  - sensor.received_eth0
  - sensor.sonoff_office_temperature
  - sensor.sonoff_office_humidity
  - sensor.living_room_temperature
  - sensor.living_room_humidity
  - sensor.sonoff_rssi
  - sensor.sonoff_uptime
  - sensor.sonoff_vcc
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - sensor.speedtest_ping
  - sensor.sent_eth0
  - sensor.stats_ratio_athome
  - sensor.trade_volume
  - sensor.uberx_price
  - sensor.uberx_time
  - vacuum.valetudo_roborock
