---
# homekit config

auto_start: false
port: 51827
advertise_ip: !secret host_ip
# safe_mode: true
filter:
  include_domains:
    - switch
    - cover
  include_entities:
    - input_boolean.loop_livingcolors_1
    - input_boolean.loop_livingcolors_2
    - light.deckenleuchte
    - light.stehlampe
    - light.hue_spot_1
    - light.hue_spot_2
    - light.hue_spot_3
    - light.schreibtischlampe
    - light.light_7
    - light.light_8
    - light.light_9
    - light.light_10
    - light.light_11
    - media_player.sony_bravia_tv
    - media_player.playstation_4
    - sensor.wemosd1_room_humidity
    - sensor.wemosd1_room_temperature
    - vacuum.roborock
  exclude_entities:
    - cover.living_room_group
    - cover.bed_room_group
entity_config:
  input_boolean.loop_livingcolors_1:
    name: "Loop 1"
  input_boolean.loop_livingcolors_2:
    name: "Loop 2"
  media_player.sony_bravia_tv:
    name: Fernseher
  media_player.playstation_4:
    name: "Playstation 4"
    feature_list:
      - feature: on_off
  sensor.wemosd1_room_humidity:
    name: "Luftfeuchtigkeit"
  sensor.wemosd1_room_temperature:
    name: "Temparatur"
  switch.magic_mirror:
    name: "Magic Mirror"
  vacuum.roborock:
    name: "Staubsauger"
