---
# homekit config

- mode: bridge
  port: 51827
  advertise_ip: !secret host_ip
  # safe_mode: true
  filter:
    include_domains:
      - switch
      - cover
    include_entity_globs:
      - input_boolean.loop_livingcolors_*
      - light.spot_*
      - light.light_*
    include_entities:
      - climate.netatmo_smart_thermostat
      - light.ceiling_lamp
      - light.floor_lamp
      - light.nachttischlampe
      - light.schreibtischlampe
      - light.color_temperature_light_15
      - media_player.playstation_4
      - script.adaptive_lighting_manual_control_reset
      - sensor.living_room_humidity
      - sensor.living_room_temperature
      - sensor.netatmo_smart_thermostat_current_temperature
      - vacuum.valetudo_roborock
    exclude_entity_globs:
      - switch.pi_hole_*
      - switch.adaptive_lighting_*
      - cover.*_group
  entity_config:
    cover.fyrtur_1:
      name: "Rollo 1"
      linked_battery_sensor: sensor.fyrtur_block_out_roller_blind_battery_level_1
    cover.fyrtur_2:
      name: "Rollo 2"
      linked_battery_sensor: sensor.fyrtur_block_out_roller_blind_battery_level_2
    cover.fyrtur_3:
      name: "Rollo 3"
      linked_battery_sensor: sensor.fyrtur_block_out_roller_blind_battery_level_3
    cover.fyrtur_4:
      name: "Rollo 4"
      linked_battery_sensor: sensor.fyrtur_block_out_roller_blind_battery_level_4
    input_boolean.loop_livingcolors_1:
      name: "Loop 1"
    input_boolean.loop_livingcolors_2:
      name: "Loop 2"
    media_player.playstation_4:
      name: "Playstation 4"
      feature_list:
        - feature: on_off
    sensor.living_room_humidity:
      name: "Luftfeuchtigkeit"
    sensor.living_room_temperature:
      name: "Temparatur"
    switch.magic_mirror:
      name: "Magic Mirror"
    switch.tv_mute:
      name: "Stummschaltung"
    vacuum.valetudo_roborock:
      name: "Staubsauger"
- name: Fernseher
  mode: accessory
  port: 51828
  advertise_ip: !secret host_ip
  filter:
    include_entities:
      - media_player.sony_bravia_tv
  entity_config:
    media_player.sony_bravia_tv:
      name: Fernseher
