---
# homekit config

- mode: bridge
  port: 51827
  advertise_ip: !secret host_ip
  # safe_mode: true
  filter:
    include_domains:
      - switch
      - cover
    include_entity_globs:
      - input_boolean.loop_livingcolors_*
      - light.hue_*
      - light.tradfri_*
    include_entities:
      - climate.netatmo_smart_thermostat
      - media_player.playstation_4
      - script.adaptive_lighting_manual_control_reset
      - sensor.living_room_humidity
      - sensor.living_room_temperature
      - sensor.netatmo_smart_thermostat_current_temperature
      - vacuum.valetudo_roborock
    exclude_entities:
      - light.hue_lwa004_light
      - light.hue_lwb010_light
    exclude_entity_globs:
      - switch.pi_hole_*
      - switch.adaptive_lighting_*
      - cover.*_group
      - media_player.homepod_*
  entity_config:
    input_boolean.loop_livingcolors_1:
      name: "Loop 1"
    input_boolean.loop_livingcolors_2:
      name: "Loop 2"
    media_player.playstation_4:
      name: "Playstation 4"
      feature_list:
        - feature: on_off
    sensor.living_room_humidity:
      name: "Luftfeuchtigkeit"
    sensor.living_room_temperature:
      name: "Temparatur"
    switch.magic_mirror:
      name: "Magic Mirror"
    switch.tv_mute:
      name: "Stummschaltung"
    vacuum.valetudo_roborock:
      name: "Staubsauger"
- name: Fernseher
  mode: accessory
  port: 51828
  advertise_ip: !secret host_ip
  filter:
    include_entities:
      - media_player.sony_bravia_tv
  entity_config:
    media_player.sony_bravia_tv:
      name: Fernseher
