---
# input configuration

wakeup_duration:
  name: Fade-in
  icon: mdi:clock-in
  initial: 10
  min: 5
  max: 60
  step: 5
wakeup_cover_open_delay:
  name: 'wake-up cover delay'
  icon: mdi:clock-in
  min: 0
  max: 60
  step: 5
wakeup_target_brightness:
  name: 'wake-up target brightness'
  icon: mdi:brightness-6
  min: 0
  max: 255
  step: 1
