---
# input configuration

loop_livingcolors_1:
  name: Loop LivingColors
loop_livingcolors_2:
  name: Loop LivingColors Stehlampe
wakeup:
  name: 'Wake up light'
  icon: mdi:power
wakeup_weekends:
  icon: mdi:calendar
  name: 'Wake up lights on weekends'
vacuum_weekends:
  icon: mdi:calendar
  name: 'Vacuum on weekends'
