---
# input configuration

time_turnoff_devices:
  name: Turn-off time devices
  has_date: false
  has_time: true
wakeup_alarm_time:
  name: Alarm
  has_date: false
  has_time: true
time_close_covers_night:
  name: Close covers
  has_date: false
  has_time: true
vacuum_schedule_1_from:
  name: Vacuum morning schedule start
  has_date: false
  has_time: true
vacuum_schedule_1_to:
  name: Vacuum morning schedule end
  has_date: false
  has_time: true
vacuum_schedule_2_from:
  name: Vacuum afternoon schedule start
  has_date: false
  has_time: true
vacuum_schedule_2_to:
  name: Vacuum afternoon schedule end
  has_date: false
  has_time: true