---

loop_livingcolors_1:
  name: Loop LivingColors
loop_livingcolors_2:
  name: Loop LivingColors Stehlampe
wakeup:
  name: 'Aufwachbeleuchtung'
  icon: mdi:power
wakeup_weekends:
  icon: mdi:calendar
vacuum_weekends:
  icon: mdi:calendar
