---
# ios configuration
push:
  categories:
    - name: Staubsauger entleeren
      identifier: 'emptyrobovac'
      actions:
        - identifier: 'EMPTY_ROBOVAC_LATER'
          title: 'später'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
        - identifier: 'EMPTY_ROBOVAC_NOW'
          title: 'jetzt'
          activationMode: 'background'
          authenticationRequired: no
          destructive: no
          behavior: 'default'
