---
# ios configuration
push:
  categories:
    - name: Staubsauger entleeren
      identifier: 'emptyroborock'
      actions:
        - identifier: 'EMPTY_ROBOROCK_LATER'
          title: 'später'
          activationMode: 'background'
          authenticationRequired: false
          destructive: false
          behavior: 'default'
        - identifier: 'EMPTY_ROBOROCK_NOW'
          title: 'jetzt'
          activationMode: 'background'
          authenticationRequired: false
          destructive: false
          behavior: 'default'
