---
# nintendo wishlist

country: AT
wishlist:
  - "80 DAYS"
  - "Untitled Goose Game"
  - "Return of the Obra Dinn"
  - "Bad North"
  - "UNDERTALE"
  - "Dead Cells"
  - "Wargroove"
  - "The Touryst"
  - "Hollow Knight"
  - "Dr. Kawashimas Gehirn-Jogging für Nintendo Switch"
  - "The Legend of Zelda: Link's Awakening"
  - "Animal Crossing: New Horizons"
