---
# notify config

- name: smtp
  platform: smtp
  server: !secret mail_acc_2_smtp
  port: 587
  timeout: 15
  sender: !secret mail_acc_2
  username: !secret mail_acc_2_user
  password: !secret mail_acc_2_pw
  encryption: starttls
  recipient:
    - !secret mail_acc_3
  sender_name: Home Assistant
- name: file
  platform: file
  filename: notifications.log
