---
# plants

Yucca aloifolia:
  sensors:
    moisture: sensor.yuccaaloifolia_moisture
    battery: sensor.yuccaaloifolia_battery
    temperature: sensor.yuccaaloifolia_temperature
    conductivity: sensor.yuccaaloifolia_conductivity
    brightness: sensor.yuccaaloifolia_light
  min_moisture: 15
  max_moisture: 60
  min_battery: 20
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 8
  max_temperature: 32
