---
# plants

Yucca aloifolia:
  sensors:
    moisture: sensor.yucca_aloifolia_moisture
    temperature: sensor.yucca_aloifolia_temperature
    conductivity: sensor.yucca_aloifolia_soil_conductivity
    brightness: sensor.yucca_aloifolia_illuminance
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 8
  max_temperature: 32

Howea forsteriana:
  sensors:
    moisture: sensor.howea_forsteriana_moisture
    temperature: sensor.howea_forsteriana_temperature
    conductivity: sensor.howea_forsteriana_soil_conductivity
    brightness: sensor.howea_forsteriana_illuminance
  min_moisture: 15
  max_moisture: 60
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 8
  max_temperature: 32
