---
# plants

Yucca Elephantipes:
  sensors:
    moisture: sensor.yuccaelephantipes_moisture
    battery: sensor.yuccaelephantipes_battery
    temperature: sensor.yuccaelephantipes_temperature
    conductivity: sensor.yuccaelephantipes_conductivity
    brightness: sensor.yuccaelephantipes_light
  min_moisture: 15
  max_moisture: 60
  min_battery: 20
  min_conductivity: 350
  max_conductivity: 2000
  min_temperature: 8
  max_temperature: 32
