---
# recorder includes

domains:
  - media_player
  - sensor
  - light
  - device_tracker
  - person
  - switch
  - automation
  - vacuum
  - cover
  - climate
entities:
  - binary_sensor.bed_occupancy
  - binary_sensor.motion_sensor
  - binary_sensor.motion_sensor_2
