---
# recorder excludes

domains:
  - frontend
entity_globs:
  - binary_sensor.window_openclose_*
  - binary_sensor.sonoff_s20_desk_*
  - sensor.sonoffs20magicmirror_version*
  - sensor.sonoffs20magicmirror_uptime*
  - sensor.sonoffs20_desk_version*
  - sensor.sonoffs20_desk_uptime*
  - sensor.wakeup_*
entities:
  - sensor.time
  - sensor.date
  - sensor.season
  - automation.automatic_theme_change
  - sensor.uptime
  - sensor.network_in_eth0
  - sensor.network_out_eth0
