---
# scenes

- id: '1579369073739'
  name: TV at night
  entities:
    input_boolean.loop_livingcolors_2:
      state: 'on'
    light.deckenleuchte:
      state: 'off'
    light.stehlampe:
      state: 'on'
    media_player.sony_bravia_tv:
      device_class: tv
      friendly_name: Sony Bravia TV
      icon: mdi:television
      source: 'Netflix'
      state: 'on'
      supported_features: 24509
      volume_level: 0.11
- id: '1579373198256'
  name: Gaming
  entities:
    input_boolean.loop_livingcolors_2:
      state: 'on'
    light.deckenleuchte:
      brightness: 2
      color_temp: 451
      friendly_name: Deckenleuchte
      is_deconz_group: false
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    media_player.sony_bravia_tv:
      source: HDMI 2
      state: 'on'
      volume_level: 0.17
    media_player.playstation_4:
      state: idle
- id: '1636967350036'
  name: Deckenleuchte Bright
  entities:
    light.deckenleuchte:
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 249
      color_temp: 432
      hs_color:
        - 29.412
        - 79.714
      rgb_color:
        - 255
        - 151
        - 51
      xy_color:
        - 0.567
        - 0.389
      is_deconz_group: false
      friendly_name: Deckenleuchte
      supported_features: 40
      state: 'on'
- id: '1636967380216'
  name: Deckenleuchte Energize
  entities:
    light.deckenleuchte:
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 249
      color_temp: 192
      hs_color:
        - 27.275
        - 16.489
      rgb_color:
        - 255
        - 232
        - 212
      xy_color:
        - 0.364
        - 0.348
      is_deconz_group: false
      friendly_name: Deckenleuchte
      supported_features: 40
      state: 'on'
- id: '1636967402493'
  name: Deckenleuchte Read
  entities:
    light.deckenleuchte:
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 249
      color_temp: 241
      hs_color:
        - 26.757
        - 32.237
      rgb_color:
        - 255
        - 209
        - 172
      xy_color:
        - 0.412
        - 0.363
      is_deconz_group: false
      friendly_name: Deckenleuchte
      supported_features: 40
      state: 'on'
- id: '1636967420154'
  name: Deckenleuchte Nightlight
  entities:
    light.deckenleuchte:
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
        - color_temp
      color_mode: color_temp
      brightness: 2
      color_temp: 451
      hs_color:
        - 29.737
        - 83.879
      rgb_color:
        - 255
        - 147
        - 41
      xy_color:
        - 0.577
        - 0.388
      is_deconz_group: false
      friendly_name: Deckenleuchte
      supported_features: 40
      state: 'on'
- id: '1636976798780'
  name: Deckenspots Bright
  entities:
    light.deckenspots:
      min_mireds: 153
      max_mireds: 500
      effect_list:
        - colorloop
      supported_color_modes:
        - color_temp
        - hs
        - xy
      color_mode: color_temp
      brightness: 249
      color_temp: 428
      hs_color:
        - 29.343
        - 78.812
      rgb_color:
        - 255
        - 152
        - 54
      xy_color:
        - 0.564
        - 0.389
      is_deconz_group: true
      all_on: true
      friendly_name: Deckenspots
      supported_features: 44
      custom_ui_state_card: state-card-custom-light
      state: 'on'
- id: '1636976828733'
  name: Deckenspots Energize
  entities:
    light.deckenspots:
      min_mireds: 153
      max_mireds: 500
      effect_list:
        - colorloop
      supported_color_modes:
        - color_temp
        - hs
        - xy
      color_mode: xy
      brightness: 249
      hs_color:
        - 120
        - 3.922
      rgb_color:
        - 245
        - 255
        - 245
      xy_color:
        - 0.3186
        - 0.3395
      is_deconz_group: true
      all_on: true
      friendly_name: Deckenspots
      supported_features: 44
      custom_ui_state_card: state-card-custom-light
      state: 'on'
- id: '1636976844228'
  name: Deckenspots Read
  entities:
    light.deckenspots:
      min_mireds: 153
      max_mireds: 500
      effect_list:
        - colorloop
      supported_color_modes:
        - color_temp
        - hs
        - xy
      color_mode: color_temp
      brightness: 249
      color_temp: 241
      hs_color:
        - 26.757
        - 32.237
      rgb_color:
        - 255
        - 209
        - 172
      xy_color:
        - 0.412
        - 0.363
      is_deconz_group: true
      all_on: true
      friendly_name: Deckenspots
      supported_features: 44
      custom_ui_state_card: state-card-custom-light
      state: 'on'
- id: '1636976862843'
  name: Deckenspots Nightlight
  entities:
    light.deckenspots:
      min_mireds: 153
      max_mireds: 500
      effect_list:
        - colorloop
      supported_color_modes:
        - color_temp
        - hs
        - xy
      color_mode: color_temp
      brightness: 2
      color_temp: 497
      hs_color:
        - 30.548
        - 93.899
      rgb_color:
        - 255
        - 137
        - 15
      xy_color:
        - 0.597
        - 0.383
      is_deconz_group: true
      all_on: true
      friendly_name: Deckenspots
      supported_features: 44
      custom_ui_state_card: state-card-custom-light
      state: 'on'
