---
# switch configuration

- platform: template
  switches:
    magic_mirror:
      value_template: >
        {% if is_state('binary_sensor.raspberry_pi', 'off') %}
         False
        {% else %}
         True
        {% endif %}
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sonoff_s20_magicmirror_relay
      turn_off:
        service: script.magic_mirror_shutdown
