---
# zone configuration

- name: !secret zone1_name
  latitude: !secret zone1_lat
  longitude: !secret zone1_long
  radius: 100
  icon: !secret zone1_icon
- name: !secret zone2_name
  latitude: !secret zone2_lat
  longitude: !secret zone2_long
  radius: 100
  icon: !secret zone2_icon
- name: !secret zone4_name
  latitude: !secret zone4_lat
  longitude: !secret zone4_long
  radius: 100
  icon: !secret zone4_icon
