---
# zone configuration

- name: home
  latitude: !secret hass_config_lat
  longitude: !secret hass_config_long
  radius: 100
  icon: mdi:home
- name: !secret zone00_name
  latitude: !secret hass_config_lat
  longitude: !secret hass_config_long
  radius: 100
  icon: mdi:home
  passive: true
- name: !secret zone1_name
  latitude: !secret work1_lat
  longitude: !secret work1_long
  radius: 100
  icon: mdi:domain
