---
# redacted secrets file

darksky_ak: top1secretapikey
device1: device_tracker.device_1
device2: device_tracker.device_2
dnsip_hostname: example.domain.com
favicon: '/local/blub.png'
hass_baseurl: http://example.domain.com
hass_config_lat: 17.140005
hass_config_long: 19.644145
hass_tz: America/Detroit
host_ip: 127.0.0.1
mail_acc_2: mail2@mail.com
mail_acc_2_pw: password
mail_acc_2_smtp: example.domain.com
mail_acc_2_user: username
mail_acc_3: mail@mail.com
mqtt-int_port: 80
mqtt_ip: 127.0.0.1
mqtt_password: password
mqtt_user: username
mysql_db: mysql://user:password@example.domain.com/database?charset=utf8
name_1: jim
notify_ios: notify.some_phone
path_fail2ban: /tmp/fail2ban.log
person_1: person.jim
person_1_id: jim
person_1_name: Jim
person_1_uid: jimbo1234567
proxy_ip: 127.0.0.1
ps4waker_host: http://127.0.0.1:80
ps4_ip: 127.0.0.1
robovac_devid: password
robovac_ip: 127.0.0.1
robovac_localkey: password
router_ip: 127.0.0.1
router_login: username
router_ssh: /tmp/sshkey
rpi_ip: 127.0.0.1
rpi_shutdown_command: 'touch myass'
ssl_domain: example.com
template_1: '{% if states("person.jim") != "home" %}false{% else %}true{% endif %}'
work1_lat: 17.140005
work1_long: 19.644145
workday_country: BR
workday_province: AC
zone00_name: zonename
zone1_friendly_name: zonename
zone1_fullname: zone.zonename
zone1_name: zonename2
