---
# redacted secrets file

device_1: device_tracker.device_1
f2b_jail1: a
f2b_jail2: b
f2b_jail3: c
f2b_jail4: d
f2b_jail5: e
f2b_jail1_sensor: sensor.fail2ban_a
f2b_jail2_sensor: sensor.fail2ban_b
f2b_jail3_sensor: sensor.fail2ban_c
f2b_jail4_sensor: sensor.fail2ban_d
f2b_jail5_sensor: sensor.fail2ban_e
f2b_jail1_sensor_name: a
f2b_jail2_sensor_name: b
f2b_jail3_sensor_name: c
f2b_jail4_sensor_name: d
f2b_jail5_sensor_name: e
hass_config_lat: 17.140005
hass_config_long: 19.644145
hass_tz: America/Detroit
host_ip: 127.0.0.1
mail_acc_2: mail2@mail.com
mail_acc_2_pw: password
mail_acc_2_smtp: example.domain.com
mail_acc_2_user: username
mail_acc_3: mail@mail.com
meteo_country: 'Netherlands'
meteo_province: 'Groningen'
mysql_db: mysql://user:password@example.domain.com/database?charset=utf8
name_1: jim
notify_ios: notify.some_phone
path_fail2ban: /tmp/fail2ban.log
person_1: person.jim
phoscon_url: 'https://abc.de'
proxy_ip: 127.0.0.1
ps4waker_host: http://127.0.0.1:80
ps4_ip: 127.0.0.1
rpi_ip: 127.0.0.1
rpi_shutdown_command: 'touch myass'
ssl_domain: example.com
template_1: '{% if states("person.jim") != "home" %}false{% else %}true{% endif %}'
valetudo_url: 'https://abc.de'
workday_country: BR
workday_province: AC
zone1_name: Home
zone1_lat: 17.140005
zone1_long: 19.644145
zone1_icon: mdi:home
zone2_name: B
zone2_lat: 17.140005
zone2_long: 19.644145
zone2_icon: mdi:home
zone3_name: C
zone3_lat: 17.140005
zone3_long: 19.644145
zone3_icon: mdi:home
zone4_name: D
zone4_lat: 17.140005
zone4_long: 19.644145
zone4_icon: mdi:home
