- alias: Automatic Theme Change
  id: '84938322222'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            basics
          {% else %}
            darkblue
          {% endif %}

- alias: SSL expiry notification
  id: '1500779870955'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry
    below: 21
  action:
    service: !secret notify_ios
    data_template:
      message: Warning - SSL certificate expires in {{ states.sensor.ssl_certificate_expiry.state
        }} days and has not been automatically renewed.

- alias: Update notifications
  id: '49494'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: !secret notify_ios
    data_template:
      message: Home Assistant {{ states.updater.updater.state }} is now available.

- alias: Disk Use Alarm
  id: '7592974'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_
    above: 90
  action:
    service: !secret notify_ios
    data_template:
      message: Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_.state
        }}%!

- alias: Lights and TV off
  id: '756390032'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == (states.input_datetime.time_turnoff_devices.attributes.timestamp
      | int | timestamp_custom("%H:%M", False)) }}'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data:
      entity_id:
      - switch.braviatv_1
      - light.zimmer

- alias: Sonoff-Tasmota update availability
  id: '111999111'
  trigger:
    platform: time
    at: 09:15:00
  condition:
    condition: template
    value_template: '{{ states.sensor.sonoff_maddox_version.state | replace("v", "")
      | replace(".","") != states.sensor.sonoff_3028_version.state | replace(".","")
      }}'
  action:
  - service: !secret notify_ios
    data_template:
      message: 'Sonoff-Tasmota version {{ states.sensor.sonoff_maddox_version.state
        | replace("v", "") }} is available. Do you wish to upgrade? Changelog: https://is.gd/I8U8dS'
      data:
        push:
          category: sonoffupdate

- alias: Update Sonoff-Tasmota
  id: '999111999'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: UPDATE_SONOFF
  action:
  - service: script.1515151540311

- alias: get sonoff 3028 version
  id: '1500581870914'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: 09:00:00
  action:
  - service: script.2215152489107

- alias: left home device1
  id: '1515583360531'
  trigger:
  - entity_id: !secret device1
    for:
      minutes: 5
    from: home
    platform: state
    to: not_home
  action:
  - data:
      entity_id: light.zimmer
    service: light.turn_off
  - data:
      entity_id: media_player.playstation_4
    service: media_player.turn_off
  - data:
      entity_id: media_player.braviatv_1
    service: media_player.turn_off
  - data:
      entity_id: switch.mopidy
    service: switch.turn_off
  - data:
      entity_id: light.buro
    service: light.turn_off

#- action:
#  - data:
#      entity_id: media_player.braviatv_2
#    service: media_player.turn_off
#  alias: left home device2
#  id: '9915583360531'
#  trigger:
#  - entity_id: !secret device2
#    for:
#      minutes: 5
#    from: home
#    platform: state
#    to: not_home

- alias: Log Level
  id: '1500589870955'
  trigger:
    platform: state
    entity_id: input_select.log_level
  condition:
    condition: template
    value_template: '{{ states.input_select.log_level.state != "none" }}'
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: '{{ trigger.to_state.state }}'

- alias: WakeUp Light Bedroom
  id: '1500581870955'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state
      }}'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: state
      entity_id: !secret device1
      state: home
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.wakeup_weekends
        state: 'on'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: script.wakeup_zimmer

- alias: Hue Scene Activation
  id: '1500589870955'
  trigger:
    platform: state
    entity_id: input_select.hue_scenes
  condition:
    condition: template
    value_template: '{{ states.input_select.hue_scenes.state != "none" }}'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Zimmer
      scene_name: '{{ trigger.to_state.state }}'
  - delay:
      seconds: 3
  - service: input_select.select_option
    data:
      entity_id: input_select.hue_scenes
      option: "none"

- alias: Random light
  id: '33223'
  trigger:
    platform: time
    minutes: /2
    seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_livingcolors
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.deckenspots
    data:
      effect: random
      transition: 5
      brightness: 255

- alias: Gaming PS4
  id: '1519076898412'
  trigger:
  - entity_id: media_player.playstation_4
    platform: state
    to: playing
  condition:
  - after: '19:00:00'
    condition: time
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: !secret device1
    state: home
  action:
  - data:
      group_name: Zimmer
      scene_name: Arctic aurora
    service: hue.hue_activate_scene

- alias: Stop playing PS4
  id: '1519077187087'
  trigger:
  - entity_id: media_player.playstation_4
    from: playing
    platform: state
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - after: '21:00:00'
    condition: time
  - condition: state
    entity_id: !secret device1
    state: home
  action:
  - data:
      group_name: Zimmer
      scene_name: Nightlight
    service: hue.hue_activate_scene

- alias: Ready for bed
  id: '1519077406569'
  trigger:
  - at: '21:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: !secret device1
    state: home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      group_name: Zimmer
      scene_name: Nightlight
    service: hue.hue_activate_scene

#- alias: SC Tiles update info
#  trigger:
#    platform: state
#    entity_id: sensor.sc_tiles_latest_version
#  action:
#    service: persistent_notification.create
#    data:
#      title: Update available
#      message: A new version for [Tiles custom state card](https://github.com/c727/home-assistant-tiles#changelog) is available.

- alias: Random light - Stehlampe
  id: '20180513163100'
  trigger:
    platform: time
    minutes: /2
    seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.loop_livingcolors_stehlampe
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.zimmer
    data:
      effect: random
      transition: 5
      brightness: 132