homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hass_config_lat
  longitude: !secret hass_config_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 158
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret hass_tz
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_global.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: es5
  themes: !include_dir_merge_named themes
  #extra_html_url:
  #  - /local/custom_ui/state-card-custom-light.html
  #  - /local/custom_ui/state-card-custom-toggle-url.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-light.html
    - /local/custom_ui/state-card-custom-toggle-url.html
    #- /local/custom_ui/state-card-tiles_es5.html

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
  #- name: tiles
  #  sidebar_title: Tiles
  #  sidebar_icon: mdi:view-dashboard
  #  url_path: tiles
  #  config:
  #    entities:
  #      - entity: input_boolean.switch1
  #        label: Switch 1

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  base_url: !secret hass_baseurl
  #ssl_certificate: !secret hass_sslcert
  #ssl_key: !secret hass_sslkey
  #ip_ban_enabled: true
  #login_attempts_threshold: 10

#cloud:

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  db_url: !secret mysql_db
  purge_interval: 1
  purge_keep_days: 7
  include: !include recorder_include.yaml
  exclude: !include recorder_exclude.yaml

# Enables support for tracking state changes over time.
history:
  #exclude: !include history_exclude.yaml
  include: !include history_include.yaml

customizer:
  custom_ui: local

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    homeassistant.components.http.ban: warning

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: 'de'

map:

group: !include groups.yaml

automation: !include automations.yaml

mqtt:
  broker: !secret host_ip
  port: !secret mqtt-int_port
  client_id: homeassistant-1
  username: !secret mqtt_uname
  password: !secret mqtt_pw
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

#calendar:
#  - platform: caldav
#    url: !secret caldav_url
#    username: !secret caldav_user
#    password: !secret caldav_pw
#    calendars:
#      - !secret caldav_cal


hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true

#history_graph: !include history_graph.yaml
#  graph_room_climate:
#    entities:
#      - sensor.sonoff_room_temperature
#      - sensor.sonoff_room_humidty

#apiai:
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
#input_number: !include input_number.yaml
input_select: !include input_select.yaml
#intent_script: !include intent_script.yaml
ios: !include ios.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
sensor: !include sensor.yaml
script: !include scripts.yaml
switch: !include switch.yaml
weblink: !include weblink.yaml
zone: !include zone.yaml
