homeassistant:
  name: Home
  latitude: !secret hass_config_lat
  longitude: !secret hass_config_long
  elevation: 158
  unit_system: metric
  time_zone: !secret hass_tz
  customize: !include_dir_merge_named customization/customize/
  customize_domain: !include customization/customize_domain.yaml
  customize_glob: !include customization/customize_global.yaml
  auth_providers:
    - type: homeassistant
   # - type: legacy_api_password
   #   api_password: !secret http_password
  whitelist_external_dirs:
    - /tmp/diskinfo

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip
  base_url: !secret hass_baseurl

# panel_iframe:
#   # portainer:
#   #   title: 'Portainer'
#   #   url: !secret portainer_url
#   kibana:
#     title: 'Kibana'
#     url: !secret kibana_url
#     icon: mdi:alpha-k-box

# default config
automation: !include_dir_merge_list automation/
config:
conversation:
# discovery:
#   ignore:
#     - google_cast
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
history:
  include: !include history_include.yaml
logbook:
logger:
  default: error
  logs:
    homeassistant.components.http.ban: warning
    # homeassistant.components.homekit: debug
    # pyhap: debug
    # pydeconz: debug
    # homeassistant.components.deconz: debug
lovelace: !include lovelace/lovelace.yaml
map:
mobile_app:
person: !include person.yaml
recorder:
  db_url: !secret mysql_db
  purge_interval: 1
  purge_keep_days: 30
  include: !include recorder_include.yaml
  exclude: !include recorder_exclude.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named script/
# ssdp:
sun:
system_health:
updater:
  reporting: false
zeroconf:

### one liners
binary_sensor: !include binary_sensor.yaml
breaking_changes:
# camera: !include camera.yaml
counter: !include counter.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
# light: !include light.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
plant: !include plant.yaml
sensor: !include_dir_merge_list sensor/
shell_command: !include shell_command.yaml
switch: !include switch.yaml
# websocket_api:
zone: !include zone.yaml

### other components
asuswrt:
  host: !secret router_ip
  username: !secret router_login
  ssh_key: !secret router_ssh
  sensors:
    - upload
    - download

hacs:
  token: !secret github_at
  sidepanel_icon: hacs:hacs
  options:
    release_limit: 10

eufy_vacuum:
  devices:
    - name: Robovac
      address: !secret robovac_ip
      access_token: !secret robovac_localkey
      id: !secret robovac_devid
      type: T2118

mqtt:
  broker: !secret host_ip
  port: !secret mqtt-int_port
  client_id: homeassistant-1
  username: !secret mqtt_uname
  password: !secret mqtt_pw
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

owntracks:
  max_gps_accuracy: 200
  waypoints: True
  waypoint_whitelist:
    - !secret name_1
    - !secret name_2
  new_device_defaults:
    track_new_devices: false

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  scan_interval:
    hours: 3

weather:
  - platform: darksky
    api_key: !secret darksky_ak
    mode: daily
