- platform: braviatv_psk
  name: braviatv_1
  host: !secret tv_tv1_ip
  psk: !secret tv_tv1_psk
  mac: !secret tv_tv1_mac
  android: true
- platform: ps4_node
  host: !secret ps4waker_host
  ps4_ip: !secret ps4_ip
  imagemap_json: https://raw.githubusercontent.com/Knapoc/homeassistant-config/master/games.json
