title: Home

resources:
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module
  # - url: /hacsfiles/weather-card/weather-card.js
  #   type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  # - url: /hacsfiles/lovelace-browser-commander/browser-commander.js
  #   type: js
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: js
  - url: /hacsfiles/nintendo-wishlist-card/nintendo-wishlist-card.js
    type: js
  - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/search-card/search-card.js
    type: module
  - url: /hacsfiles/gauge-card/gauge-card.js
    type: js

custom_header:
  compact_mode: true
  #background: var(--app-header-background-color);
  # hide_header: true
  voice_hide: true
  hide_config: true
  hidden_tab_redirect: false
  hide_tabs:
   - plants
   - settings
   - price
  
x-vacuum-buttons: &vacuum-buttons
  color: auto
  entity: vacuum.robovac
  size: 25%

#background: center / cover repeat-y url("/local/background/dark-wp.jpg") fixed

excluded_entities: !include /config/lovelace/excluded-entities.yaml

views: !include_dir_merge_list lovelace/views/
