title: Home

resources:
  - url: /customcards/custom-lovelace/card-tools.js?track=true
    type: js
  - url: /customcards/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /customcards/custom-lovelace/compact-custom-header/compact-custom-header.js?track=true
    type: module
  - url: /customcards/custom-lovelace/mini-graph-card-bundle.js
    type: module
  - url: /customcards/custom-lovelace/tracker-card.js?track=true
    type: module
  - url: /customcards/custom-lovelace/browser-commander.js
    type: js
  - url: /customcards/custom-lovelace/slider-entity-row.js
    type: js
  - url: /customcards/custom-lovelace/vertical-stack-in-card.js
    type: js
  - url: /customcards/custom-lovelace/button-card.js
    type: module
  - url: /customcards/custom-lovelace/fold-entity-row.js
    type: js

x-vacuum-buttons: &vacuum-buttons
  color: auto
  color_off: rgb(68, 115, 158)
  entity: vacuum.robovac
  size: 25%

background: center / cover repeat-y url("/local/background/dark-wp.jpg") fixed

views:
  - icon: mdi:home
    title: Home
    cards:
      - type: custom:compact-custom-header
        main_config: true
        background_image: true
      - type: vertical-stack
        cards:
          - type: entities
            title: Familie
            show_header_toggle: false
            entities:
              - !secret person_1
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Temperatur
                points_per_hour: 2
                font_size: 65
                entities:
                  - sensor.wemosd1_room_temperature
              - type: custom:mini-graph-card
                name: Luftfeuchtigkeit
                points_per_hour: 2
                font_size: 65
                entities:
                  - sensor.wemosd1_room_humidty
          - type: plant-status
            entity: plant.howea_forsteriana
          # - type: plant-status
          #   entity: plant.yucca_elephantipes
          - type: glance
            title: Verkehr
            entities:
              - entity: sensor.google_travel_time_dev1_transit
                name: Arbeitsweg
              - entity: sensor.google_travel_time_dev1_dynamic_home
                name: Heimweg
              - entity: sensor.uberx_time
                name: UberX
              - entity: sensor.uberx_price
                name: UberX
      - type: vertical-stack
        cards:
          - type: picture-glance
            title: Wohnzimmer
            entities:
              - media_player.braviatv_1
              - media_player.playstation_4
              - light.deckenleuchte
              - light.stehlampe
            state_image:
              "on": /local/ui-pics/wohnzimmer.png
              "off": /local/ui-pics/wohnzimmer_bw.png
            entity: group.wohnzimmer
          - type: custom:vertical-stack-in-card
            cards:
              - type: glance
                title: Staubsauger
                entities:
                  - entity: sensor.robovac_status
                    icon: mdi:robot-vacuum
                  - sensor.robovac_battery
                  - sensor.robovac_fanspeed
                  - entity: counter.vacuum_counter
                    name: '#'
              #- type: entities
              #  show_header_toggle: false
              #  entities:
              #    - type: divider
              - type: horizontal-stack
                cards:
                  - type: custom:button-card
                    <<: *vacuum-buttons
                    icon: mdi:play
                    show_name: false
                    tap_action:
                      action: call-service
                      service: vacuum.turn_on
                      service_data:
                        entity_id: vacuum.robovac
                  - type: custom:button-card
                    <<: *vacuum-buttons
                    icon: mdi:stop
                    show_name: false
                    tap_action:
                      action: call-service
                      service: vacuum.turn_off
                      service_data:
                        entity_id: vacuum.robovac
                  - type: custom:button-card
                    <<: *vacuum-buttons
                    icon: mdi:pause
                    show_name: false
                    tap_action:
                      action: call-service
                      service: vacuum.pause
                      service_data:
                        entity_id: vacuum.robovac
              - type: horizontal-stack
                cards:
                  - type: custom:button-card
                    <<: *vacuum-buttons
                    icon: mdi:vector-circle
                    show_name: false
                    tap_action:
                      action: call-service
                      service: vacuum.clean_spot
                      service_data:
                        entity_id: vacuum.robovac
                  - type: custom:button-card
                    <<: *vacuum-buttons
                    icon: mdi:bell-ring
                    show_name: false
                    tap_action:
                      action: call-service
                      service: vacuum.locate
                      service_data:
                        entity_id: vacuum.robovac
                  - type: custom:button-card
                    <<: *vacuum-buttons
                    icon: mdi:delete-empty
                    show_name: false
                    tap_action:
                      action: call-service
                      service: counter.reset
                      service_data:
                        entity_id: counter.vacuum_counter
                  #- type: custom:button-card
                  #  <<: *vacuum-buttons
                  #  icon: mdi:delete-empty
                  #  show_name: false
                  #  tap_action:
                  #    action: call-service
                  #    service: vacuum.return_to_base
                  #    service_data:
                  #      entity_id: vacuum.robovac
              - type: entities
                show_header_toggle: false
                entities:
                  #- type: divider
                  - type: custom:fold-entity-row
                    head:
                      type: section
                      label: Automatisierung
                    items:
                      - automation.robovac_auto_turn_on
                      - automation.robovac_clean_notification
                      - automation.robovac_cleaned
      - type: vertical-stack
        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
            icons: "/local/custom-lovelace/weather-card/icons/"
          - type: entities
            title: Beleuchtung
            show_header_toggle: false
            entities:
              - type: custom:slider-entity-row
                entity: light.deckenleuchte
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.stehlampe
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.deckenspots
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.kuche
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.vorzimmer
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.badezimmer
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row
                entity: light.toilette
                toggle: true
                hide_when_off: true

  - title: Wohnzimmer
    icon: mdi:sofa
    cards:
      - type: custom:compact-custom-header
        background_image: true
      - type: media-control
        entity: media_player.braviatv_1
      - type: media-control
        entity: media_player.playstation_4
      - type: entities
        title: Deckenleuchte
        show_header_toggle: false
        entities:
          - light.deckenleuchte
      - type: entities
        title: Stehlampe
        entities:
          - light.stehlampe
          - input_boolean.loop_livingcolors_2
      - type: entities
        title: Anderes
        show_header_toggle: false
        entities:
          - input_datetime.time_turnoff_devices

  - title: Schlafzimmer
    icon: mdi:bed-empty
    cards:
      - type: custom:compact-custom-header
        background_image: true
      - type: entities
        title: Deckenspots
        show_header_toggle: false
        entities:
          - light.deckenspots
          - light.hue_color_spot_1
          - light.hue_color_spot_2
          - light.hue_color_spot_3
          - script.scene_bright
          - script.scene_nightlight
          - input_boolean.loop_livingcolors_1
      
      - type: entities
        title: Beleuchtungsszenen
        entities:
          - script.scene_tropical_twilight
          - script.scene_arctic_aurora
          - script.scene_spring_blossom
          - input_select.hue_scenes
      - type: custom:vertical-stack-in-card
        title: Aufwachbeleuchtung
        cards:
          - type: entities
            entities:
              - input_boolean.wakeup
          - type: conditional
            conditions:
              - entity: input_boolean.wakeup
                state: 'on'
            card:
              type: entities
              entities:
                - input_datetime.wakeup_alarm_time
                - input_number.wakeup_duration
                - input_boolean.wakeup_weekends

  - icon: mdi:arrow-right-drop-circle
    title: Automatisierung
    cards:
      - type: custom:compact-custom-header
        background_image: true
      - type: glance
        title: Presence
        entities:
          - entity: automation.left_home_device1
            tap_action:
              action: toggle
          - entity: automation.turn_on_magic_mirror
            tap_action:
              action: toggle
          - entity: automation.turn_off_magic_mirror
            tap_action:
              action: toggle
      - type: glance
        title: Light & scenes
        columns: 3
        entities:
          - entity: automation.gaming_ps4
            tap_action:
              action: toggle
          - entity: automation.hue_scene_activation
            tap_action:
              action: toggle
          - entity: automation.lights_and_tv_off
            tap_action:
              action: toggle
          - entity: automation.random_light
            tap_action:
              action: toggle
          - entity: automation.random_light_stehlampe
            tap_action:
              action: toggle
          - entity: automation.ready_for_bed
            tap_action:
              action: toggle
          - entity: automation.stop_playing_ps4
            tap_action:
              action: toggle
          - entity: automation.wakeup_light_bedroom
            tap_action:
              action: toggle
      - type: glance
        title: Server
        columns: 3
        entities:
          - entity: automation.disk_use_alarm
            tap_action:
              action: toggle
          - entity: automation.log_level
            tap_action:
              action: toggle
          - entity: automation.ssl_expiry_notification
            tap_action:
              action: toggle
          - entity: automation.startup_theme
            tap_action:
              action: toggle
          - entity: automation.update_notifications
            tap_action:
              action: toggle
  - title: IoT
    icon: mdi:chip
    cards:
      - type: custom:compact-custom-header
        background_image: true
      - type: entities
        show_header_toggle: false
        entities:
          - entity: switch.magic_mirror
            name: Magic Mirror
          - entity: switch.magic_mirror_power
            name: S20 - Magic Mirror
      - type: vertical-stack
        cards:
          - type: glance
            title: S20 - MM
            entities:
              - entity: sensor.s20_mm_version
              - entity: sensor.s20_mm_uptime
              - entity: sensor.s20_mm_vcc
              - entity: sensor.s20_mm_rssi
      - type: vertical-stack
        cards:
          - type: glance
            title: wemosd1 - 1
            entities:
              - entity: sensor.wemosd1_version
              - entity: sensor.wemosd1_uptime
              - entity: sensor.wemosd1_vcc
              - entity: sensor.wemosd1_rssi
  - icon: mdi:server
    title: Server
    cards:
      - type: custom:compact-custom-header
        background_image: true
      - type: vertical-stack
        cards:
          - type: custom:mini-graph-card
            name: Frequenz
            points_per_hour: 2
            line_color: red
            font_size: 65
            entities:
              - sensor.cpu_speed
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.cpu_temperature
                min: 0
                max: 100
                severity:
                  green: 0
                  yellow: 45
                  red: 60
              - type: gauge
                entity: sensor.processor_use
                min: 0
                max: 100
                severity:
                  green: 0
                  yellow: 45
                  red: 80
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.memory_use_percent
                min: 0
                max: 100
                severity:
                  green: 0
                  yellow: 45
                  red: 80
              - type: gauge
                entity: sensor.swap_use_percent
                min: 0
                max: 100
                severity:
                  green: 0
                  yellow: 50
                  red: 80
              - type: gauge
                entity: sensor.disk_use_percent
                min: 0
                max: 100
                severity:
                  green: 0
                  yellow: 60
                  red: 80
          - type: glance
            title: Database
            entities:
              - entity: sensor.database_size_hass
                name: Home-Assistant
                format: relative
              - entity: sensor.database_size_nc
                name: Nextcloud
      - type: vertical-stack
        cards:
          - type: glance
            title: fail2ban
            entities:
              - entity: sensor.fail2ban_homeassistant
                name: Homeassistant
              - entity: sensor.fail2ban_nextcloud
                name: Nextcloud
              - entity: sensor.fail2ban_sshd
                name: SSH
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Download
                line_color: "#4169E1"
                font_size: 65
                entities:
                  - sensor.speedtest_download
              - type: custom:mini-graph-card
                name: Upload
                line_color: orange
                font_size: 65
                entities:
                  - sensor.speedtest_upload
              - type: custom:mini-graph-card
                name: Ping
                line_color: green
                font_size: 65
                entities:
                  - sensor.speedtest_ping
          - type: glance
            title: Network
            entities:
              - entity: sensor.asuswrt_download
                name: Download
                icon: mdi:download
              - entity: sensor.asuswrt_upload
                name: Upload
                icon: mdi:upload
              - entity: sensor.network_in_eth0
                name: eth0 - in
                icon: mdi:download
              - entity: sensor.network_out_eth0
                name: eth0 - out
                icon: mdi:download
      - type: vertical-stack
        cards:
          - type: entities
            title: Uptime
            show_header_toggle: false          
            entities:
              - entity: sensor.last_boot
                name: Server
                format: relative
              - entity: sensor.uptime
                name: Home-Assistant
          - type: entities
            title: other
            show_header_toggle: false
            entities:
              - entity: input_select.log_level
          - type: entities
            title: Links
            show_header_toggle: false
            entities:
              - type: weblink
                name: ASUS RT-AC68U
                url: !secret router_url
                icon: mdi:router-wireless
              - type: weblink
                name: pixelserv-tls
                url: !secret pixelserv_url
                icon: mdi:dns
              - type: weblink
                name: NUC-syncthing
                url: !secret nucst_url
                icon: mdi:sync
              - type: weblink
                name: Home Assistant
                url: https://www.home-assistant.io
                icon: mdi:home-assistant
  - icon: mdi:settings
    title: Administration
    cards:
      - type: custom:compact-custom-header
        background_image: true
      - type: custom:tracker-card
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.potential_breaking_changes
            name: Breaking changes
