homeassistant:
  customize:
    sensor.exchange_rate_1_btc:
      friendly_name: Kurs (1 BTC)
      homebridge_hidden: true
    input_number.btc_low:
      friendly_name: BTC low
      icon: mdi:currency-btc
      #custom_ui_state_card: state-card-custom-ui
      #state_card_mode: no-slider
    input_number.btc_high:
      friendly_name: BTC high
      icon: mdi:currency-btc
      #custom_ui_state_card: state-card-custom-ui
      #state_card_mode: no-slider

sensor:
  - platform: bitcoin
    currency: USD
    display_options:
      - exchangerate
      - trade_volume_btc

input_number:
  btc_low:
    name: Bitcoin Low Warning
    initial: 9000
    min: 1
    max: 20000
    step: 1
    mode: box
  btc_high:
    name: Bitcoin High Warning
    initial: 13000
    min: 1
    max: 20000
    step: 1
    mode: box

group:
  BTC:
    entities:
      - sensor.exchange_rate_1_btc
      - input_number.btc_low
      - input_number.btc_high
    name: Bitcoins

#automation:
#  - alias: 'BTC initial sliders'
#    id: '188077743567'
#    trigger:
#      event: start
#      platform: homeassistant
#    condition:
#      condition: template
#      value_template: '{{ states.sensor.exchange_rate_1_btc.state != "unknown" }}'
#    action:
#      - service: input_number.set_value
#        entity_id: input_number.btc_low
#        data_template: '{{ states.sensor.exchange_rate_1_btc.state | float - 200 }}'
#      - service: input_number.set_value
#        entity_id: input_number.btc_high
#        data_template: '{{ states.sensor.exchange_rate_1_btc.state | float + 200 }}'
