homeassistant:
  customize:
    input_select.log_level:
      icon: mdi:note-text

input_select:
  log_level:
    name: Log Level
    options:
      - none
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: none

automation:
  - alias: 'Log Level'
    id: '1500589870955'
    trigger:
      platform: state
      entity_id: input_select.log_level
    condition:
      condition: template
      value_template: '{{ states.input_select.log_level.state != "none" }}'
    action:
      service: logger.set_level
      data_template:
        homeassistant.components: "{{ trigger.to_state.state }}"
