blueprint:
  name: "deCONZ - Philips Hue Dimmer Switch - Custom Actions"
  description: Freely customizable actions for Philips Hue Dimmer Switch buttons.
  domain: automation
  input:
    remote:
      name: Dimmer Switch
      selector:
        device:
          integration: deconz
          manufacturer: Philips
          entity:
            domain: sensor
            device_class: battery
    button_one_short_release:
      name: Button 1 short release actions
      default: []
      selector:
        action: {}
    button_one_hold:
      name: Button 1 hold actions
      default: []
      selector:
        action: {}
    button_one_long_release:
      name: Button 1 long release actions
      default: []
      selector:
        action: {}
    button_two_short_release:
      name: Button 2 short release actions
      default: []
      selector:
        action: {}
    button_two_hold:
      name: Button 2 hold actions
      default: []
      selector:
        action: {}
    button_two_long_release:
      name: Button 2 long release actions
      default: []
      selector:
        action: {}
    button_three_short_release:
      name: Button 3 short release actions
      default: []
      selector:
        action: {}
    button_three_hold:
      name: Button 3 hold actions
      default: []
      selector:
        action: {}
    button_three_long_release:
      name: Button 3 long release actions
      default: []
      selector:
        action: {}
    button_four_short_release:
      name: Button 4 short release actions
      default: []
      selector:
        action: {}
    button_four_hold:
      name: Button 4 hold actions
      default: []
      selector:
        action: {}
    button_four_long_release:
      name: Button 4 long release actions
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input remote

action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      - conditions:
          - "{{ event == 1002 }}"
        sequence: !input button_one_short_release
      - conditions:
          - "{{ event == 1001 }}"
        sequence: !input button_one_hold
      - conditions:
          - "{{ event == 1003 }}"
        sequence: !input button_one_long_release
      - conditions:
          - "{{ event == 2002 }}"
        sequence: !input button_two_short_release
      - conditions:
          - "{{ event == 2001 }}"
        sequence: !input button_two_hold
      - conditions:
          - "{{ event == 2003 }}"
        sequence: !input button_two_long_release
      - conditions:
          - "{{ event == 3002 }}"
        sequence: !input button_three_short_release
      - conditions:
          - "{{ event == 3001 }}"
        sequence: !input button_three_hold
      - conditions:
          - "{{ event == 3003 }}"
        sequence: !input button_three_long_release
      - conditions:
          - "{{ event == 4002 }}"
        sequence: !input button_four_short_release
      - conditions:
          - "{{ event == 4001 }}"
        sequence: !input button_four_hold
      - conditions:
          - "{{ event == 4003 }}"
        sequence: !input button_four_long_release
