---

blueprint:
  name: Time-based Light Turn Off
  description: Turn off a light based on time
  domain: automation
  input:
    light_entity:
      name: Light
      selector:
        entity:
          domain: light
    on_time:
      name: On time
      description: Time to leave the light on.
      default: 900
      selector:
        number:
          min: 0
          max: 86400
          unit_of_measurement: seconds

trigger:
  platform: state
  entity_id: !input light_entity
  from: "off"
  to: "on"
  for:
    seconds: !input on_time

action:
  - service: light.turn_off
    entity_id: !input light_entity
