---
# Lovelace excludes
- automation.roborock_auto_turn_on
- automation.roborock_clean_counter
- automation.roborock_clean_notification
- automation.roborock_cleaned
- automation.lights_and_tv_off
- automation.random_light_deckenspots
- automation.turn_off_loop_effect_deckenspots
- automation.random_light_stehlampe
- automation.turn_off_loop_effect_stehlampe
- automation.hue_scene_activation
- automation.ready_for_bed
- automation.gaming_ps4
- automation.stop_playing_ps4
- automation.wakeup_light_bedroom
