basics:
  primary-color: '#5294E2'
  dark-primary-color: '#0971B2'
  light-primary-color: '#CFD8DC'
  text-primary-color: '#FFFFFF'
  primary-text-color: '#212121'
  paper-grey-50: '#DEDEDE'
  paper-item-icon-color: '#5294E2'
  paper-toggle-button-checked-ink-color: '#5294E2'
  paper-toggle-button-checked-button-color: '#0971B2'
  paper-toggle-button-checked-bar-color: '#5294E2'
  paper-toggle-button-unchecked-button-color: '#EAEAEA'
  paper-toggle-button-unchecked-bar-color: '#DEDEDE'
  paper-toggle-button-unchecked-ink-color: '#DEDEDE'
  paper-slider-knob-color: '#0971B2'
  paper-slider-knob-start-color: '#0971B2'
  paper-slider-pin-color: '#0971B2'
  paper-slider-active-color: '#5294E2'
  paper-slider-secondary-color: '#EAEAEA'
  paper-slider-container-color: '#DEDEDE'
  ha-label-badge-color: '#DEDEDE'
  paper-tabs-selection-bar-color: '#DEDEDE'
