# - platform: google_travel_time
#   name: google_travel_time_dev1_transit
#   api_key: !secret google_api
#   origin: !secret device1
#   destination: !secret zone1_fullname
#   options:
#     mode: transit

# - platform: google_travel_time
#   name: google_travel_time_dev1_dynamic_home
#   api_key: !secret google_api
#   origin: !secret device1
#   destination: zone.home
#   options:
#     mode: transit

# - platform: uber
#   server_token: !secret uber_st
#   end_latitude: !secret uber_endlat
#   end_longitude: !secret uber_endlong
#   product_ids:
#     - '0af354f1-e12e-4253-abae-3df48506c658'

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: file
  file_path: !secret path_disk_0
  name: disk_size_sda2
  unit_of_measurement: kB
  value_template: '{{ value_json.spacetotal }}'

- platform: file
  file_path: !secret path_disk_0
  name: disk_used_sda2
  unit_of_measurement: kB
  value_template: '{{ value_json.spaceused }}'

- platform: file
  file_path: !secret path_disk_1
  name: disk_size_sda1
  unit_of_measurement: kB
  value_template: '{{ value_json.spacetotal }}'

- platform: file
  file_path: !secret path_disk_1
  name: disk_used_sda1
  unit_of_measurement: kB
  value_template: '{{ value_json.spaceused }}'
