---
# more sensors

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: history_stats
  name: stats_ratio_athome
  entity_id: !secret person_1
  state: 'home'
  type: ratio
  end: '{{ now() }}'
  duration:
    days: 7

- platform: command_line
  name: latest_valetudo
  command: curl -s https://github.com/Hypfer/Valetudo/releases/latest | cut -d'"' -f2 | rev | cut -d'/' -f1 | rev
  scan_interval: 21600
