---

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: file
  file_path: !secret path_disk_0
  name: disk_size_sda2
  unit_of_measurement: kB
  value_template: '{{ value_json.spacetotal }}'

- platform: file
  file_path: !secret path_disk_0
  name: disk_used_sda2
  unit_of_measurement: kB
  value_template: '{{ value_json.spaceused }}'

- platform: file
  file_path: !secret path_disk_1
  name: disk_size_sda1
  unit_of_measurement: kB
  value_template: '{{ value_json.spacetotal }}'

- platform: file
  file_path: !secret path_disk_1
  name: disk_used_sda1
  unit_of_measurement: kB
  value_template: '{{ value_json.spaceused }}'
