---
# template sensors

- platform: template
  sensors:
    is_home:
      friendly_name: 'Is someone home?'
      entity_id: !secret person_1
      value_template: !secret template_1
    wakeup_start_time_lights:
      friendly_name: 'Fade-in Startzeit'
      value_template: >
        {% if states.input_datetime.wakeup_alarm_time and states.input_number.wakeup_duration %}
        {% set alarmtime = states.input_datetime.wakeup_alarm_time.state %}
        {% set alarm_hour = alarmtime.split(":")[0] | int %}
        {% set alarm_min = alarmtime.split(":")[1] | int %}
        {% set light_dur = states.input_number.wakeup_duration.state | int %}
        {% set alarm_min_light = alarm_min - light_dur %}
        {% if alarm_min_light  < 0 %}
        {% set alarm_min_light = alarm_min_light + 60 %}
        {% set alarm_hour_light = alarm_hour - 1 %}
        {% if alarm_hour_light < 0 %}{% set alarm_hour_light = 23 %}{% endif %}
        {% if alarm_hour_light < 10 %}0{% endif %}{{ alarm_hour_light}}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% else %}
        {% if alarm_hour < 10 %}0{% endif %}{{ alarm_hour }}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% endif %}
        {% endif %}
    wakeup_open_time_covers:
      friendly_name: 'Rollo öffnen Startzeit'
      value_template: >
        {% if states.input_datetime.wakeup_alarm_time and states.input_number.wakeup_cover_open_delay %}
        {% set alarmtime = states.input_datetime.wakeup_alarm_time.state %}
        {% set alarm_hour = alarmtime.split(":")[0] | int %}
        {% set alarm_min = alarmtime.split(":")[1] | int %}
        {% set cover_dur = states.input_number.wakeup_cover_open_delay.state | int %}
        {% set alarm_min_cover = alarm_min + cover_dur %}
        {% if alarm_min_cover  > 59 %}
        {% set alarm_min_cover = alarm_min_cover - 60 %}
        {% set alarm_hour_cover = alarm_hour + 1 %}
        {% if alarm_hour_cover > 23 %}{% set alarm_hour_cover = 0 %}{% endif %}
        {% if alarm_hour_cover < 10 %}0{% endif %}{{ alarm_hour_cover}}:{% if alarm_min_cover < 10 %}0{% endif %}{{ alarm_min_cover }}
        {% else %}
        {% if alarm_hour < 10 %}0{% endif %}{{ alarm_hour }}:{% if alarm_min_cover < 10 %}0{% endif %}{{ alarm_min_cover }}
        {% endif %}
        {% endif %}
    robovac_battery:
      unit_of_measurement: '%'
      friendly_name: Batterie
      value_template: '{{ states.vacuum.robovac.attributes.battery_level }}'
      icon_template: '{{ states.vacuum.robovac.attributes.battery_icon }}'
    robovac_status:
      friendly_name: Status
      value_template: '{{ states.vacuum.robovac.attributes.status }}'
    robovac_fanspeed:
      friendly_name: "Saugkraft"
      value_template: '{{ states.vacuum.robovac.attributes.fan_speed }}'
    disk_useperc_sda2:
      value_template: '{{ ((states.sensor.disk_used_sda2.state | int) / (states.sensor.disk_size_sda2.state | int) * 100) | round(1) }}'
      unit_of_measurement: '%'
    disk_useperc_sda1:
      value_template: '{{ ((states.sensor.disk_used_sda1.state | int) / (states.sensor.disk_size_sda1.state | int) * 100) | round(1) }}'
      unit_of_measurement: '%'
    count_automations:
      entity_id: sensor.date
      value_template: "{{ states.automation | list | length }}"
    count_covers:
      entity_id: sensor.date
      value_template: "{{ states.cover | list | length }}"
    count_scripts:
      entity_id: sensor.date
      value_template: "{{ states.script | list | length }}"
    count_device_trackers:
      entity_id: sensor.date
      value_template: "{{ states.device_tracker | list | length }}"
    count_binary_sensors:
      entity_id: sensor.date
      value_template: "{{ states.binary_sensor | list | length }}"
    count_sensors:
      entity_id: sensor.date
      value_template: "{{ states.sensor | list | length }}"
    count_switches:
      entity_id: sensor.date
      value_template: "{{ states.switch | list | length }}"
    count_zones:
      entity_id: sensor.date
      value_template: "{{ states.zone | list | length }}"
    count_input_booleans:
      entity_id: sensor.date
      value_template: "{{ states.input_boolean | list | length }}"
    count_input_numbers:
      entity_id: sensor.date
      value_template: "{{ states.input_number | list | length }}"
    count_input_texts:
      entity_id: sensor.date
      value_template: "{{ states.input_text | list | length }}"
    count_input_selects:
      entity_id: sensor.date
      value_template: "{{ states.input_select | list | length }}"
    count_input_datetimes:
      entity_id: sensor.date
      value_template: "{{ states.input_datetime | list | length }}"
    count_lights:
      entity_id: sensor.date
      value_template: "{{ states.light | list | length }}"
    lights_on:
      entity_id: sensor.time
      value_template: '{{ states.light | selectattr("state", "equalto", "on") | rejectattr("attributes.is_deconz_group") | list | length }}'
