---
# cover automations

- alias: 'open covers in the morning'
  id: '1583686217'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == states('sensor.wakeup_open_time_covers') }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.wakeup
        state: 'on'
      - condition: state
        entity_id: !secret person_1
        state: home
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekends
            state: 'on'
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_1', 'current_position')|int) < 100 }}"
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_2', 'current_position')|int) < 100 }}"
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_3', 'current_position')|int) < 100 }}"
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_4', 'current_position')|int) < 100 }}"
  action:
    service: cover.open_cover
    data_template:
      entity_id: >
        {% set entities = 'cover.fyrtur_1',
                          'cover.fyrtur_2',
                          'cover.fyrtur_3',
                          'cover.fyrtur_4' %}
        {{ states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','<',100) | map(attribute='entity_id') | join(', ') }}
- alias: 'close covers at night'
  id: '1583686218'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.time_close_covers_night', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret person_1
        state: home
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_1', 'current_position')|int) > 0 }}"
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_2', 'current_position')|int) > 0 }}"
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_3', 'current_position')|int) > 0 }}"
          - condition: template
            value_template: "{{ (state_attr('cover.fyrtur_4', 'current_position')|int) > 0 }}"
  action:
    service: cover.close_cover
    data_template:
      entity_id: >
        {% if is_state('binary_sensor.window_openclose_1', 'off') %}
          {% set entities = 'cover.fyrtur_1' %}
        {% endif %}
        {% if is_state('binary_sensor.window_openclose_2', 'off') %}
          {% set entities = entities + 'cover.fyrtur_2' %}
        {% endif %}
        {% if is_state('binary_sensor.window_openclose_3', 'off') %}
          {% set entities = entities + 'cover.fyrtur_3' %}
        {% endif %}
        {% if is_state('binary_sensor.window_openclose_4', 'off') %}
          {% set entities = entities + 'cover.fyrtur_4' %}
        {% endif %}
        {{ states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','>',0) | map(attribute='entity_id') | join(', ') }}
- alias: 'stop cover if window is open'
  id: '1585950689'
  trigger:
    - platform: state
      entity_id: 'cover.fyrtur_1'
      to: 'closed'
    - platform: state
      entity_id: 'cover.fyrtur_2'
      to: 'closed'
    - platform: state
      entity_id: 'cover.fyrtur_3'
      to: 'closed'
    - platform: state
      entity_id: 'cover.fyrtur_4'
      to: 'closed'
  condition:
    - condition: template
      value_template: >
        {% if trigger.entity_id == "cover.fyrtur_1" %}
          {{ is_state('binary_sensor.window_openclose_1', 'on') }}
        {% elif trigger.entity_id == "cover.fyrtur_2" %}
          {{ is_state('binary_sensor.window_openclose_2', 'on') }}
        {% elif trigger.entity_id == "cover.fyrtur_3" %}
          {{ is_state('binary_sensor.window_openclose_3', 'on') }}
        {% elif trigger.entity_id == "cover.fyrtur_4" %}
          {{ is_state('binary_sensor.window_openclose_4', 'on') }}
        {% endif %}
  action:
    service: cover.stop_cover
    data_template:
      entity_id: '{{ trigger.entity_id }}'
