---
# other automations

- alias: Turn on desk plug
  id: '1634799371'
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: state
      entity_id: !secret device_1
      to: 'home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret device_1
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: !secret person_1
        state: 'home'
      - condition: not
        conditions:
          - condition: state
            entity_id: switch.sonoff_s20_desk_relay
            state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sonoff_s20_desk_relay

- alias: Turn off desk plug
  id: '1597432590'
  trigger:
    - platform: time
      at: '19:00:00'
    - platform: state
      entity_id: !secret device_1
      to: 'not_home'
      for: '00:30:00'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.sonoff_s20_desk_relay
        state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.sonoff_s20_desk_relay

- id: '1614873068229'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      time: '10:00:00'
      actions:
        - service: notify.mobile_app_juergen_s_iphone
          data:
            message: 'Low battery warning for: {{sensors}}'
            title: Battery alert!
- id: '1623831661000'
  alias: 'Alert me about weather warnings'
  trigger:
    - platform: state
      entity_id: binary_sensor.meteoalarm
      from: 'off'
  action:
    - service: !secret notify_ios
      data:
        title: "{{state_attr('binary_sensor.meteoalarm', 'headline')}}"
        message: "{{state_attr('binary_sensor.meteoalarm', 'description')}} is effective on {{state_attr('binary_sensor.meteoalarm', 'effective')}}"
