---
# other automations

- alias: Turn on desk plug
  id: '1634799371'
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: state
      entity_id: !secret device_1
      to: 'home'
      for: '00:10:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret device_1
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: !secret person_1
        state: 'home'
      - condition: not
        conditions:
          - condition: state
            entity_id: switch.sonoff_s20_desk_relay
            state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sonoff_s20_desk_relay

- alias: Turn off desk plug
  id: '1597432590'
  trigger:
    - platform: time
      at: '19:00:00'
    - platform: state
      entity_id: !secret device_1
      to: 'not_home'
      for: '00:30:00'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.sonoff_s20_desk_relay
        state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.sonoff_s20_desk_relay

- id: '1614873068229'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 10
      time: '10:00:00'
      actions:
        - service: notify.mobile_app_juergen_s_iphone
          data:
            message: 'Low battery warning for: {{sensors}}'
            title: Battery alert!
- id: '1623831661000'
  alias: 'Alert me about weather warnings'
  trigger:
    - platform: state
      entity_id: binary_sensor.meteoalarm
      from: 'off'
  action:
    - service: !secret notify_ios
      data:
        title: "{{state_attr('binary_sensor.meteoalarm', 'headline')}}"
        message: >-
          {% if state_attr('binary_sensor.meteoalarm', 'description')[-1] == '.' %}
          {{state_attr('binary_sensor.meteoalarm', 'description')[:-1]}}
          {% else %}
          {{state_attr('binary_sensor.meteoalarm', 'description')}}
          {% endif %}from {{as_datetime(state_attr('binary_sensor.meteoalarm', 'onset'))}}
          to {{as_datetime(state_attr('binary_sensor.meteoalarm', 'expires'))}}.


          Is effective on {{as_datetime(state_attr('binary_sensor.meteoalarm', 'effective'))}}.
- id: '1707664879654'
  alias: Heating Off
  description: Turn heating off when window is open
  trigger:
    - type: opened
      platform: device
      device_id: 14423fd9e2a59453630becf97956e896
      entity_id: 8b9ef118ebaaa118896182c382ecd866
      domain: binary_sensor
      for:
        hours: 0
        minutes: 1
        seconds: 0
  condition:
    - condition: device
      device_id: 88f536dd455073e66b17687ec3f776fa
      domain: climate
      entity_id: ea2a31b656e647cd7eb46acdc735a8b9
      type: is_hvac_mode
      hvac_mode: heat
  action:
    - device_id: 88f536dd455073e66b17687ec3f776fa
      domain: climate
      entity_id: ea2a31b656e647cd7eb46acdc735a8b9
      type: set_hvac_mode
      hvac_mode: 'off'
  mode: single
- id: '1707665331477'
  alias: Open Cover
  description: open cover when window is opened
  trigger:
    - type: opened
      platform: device
      device_id: 5f2fc311dce06e260e9d375665dc8576
      entity_id: a029c6d9ac4f1e3855b09a2a1e5afe69
      domain: binary_sensor
  condition:
    - condition: device
      device_id: d4ff25e33bb75dccf5c824175d7be0bb
      domain: cover
      entity_id: 7cfb0d771d472e73dd3a24cac40b1510
      type: is_position
      below: 60
  action:
    - service: cover.open_cover
      metadata: {}
      data: {}
      target:
        device_id: d4ff25e33bb75dccf5c824175d7be0bb
  mode: single
