---
# other automations

- alias: Turn on desk plug
  id: '1597432589'
  trigger:
    - platform: time
      at: '07:00:00'
    - platform: state
      entity_id: !secret device3
      to: 'home'
      for: '00:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret device3
        state: 'home'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: state
        entity_id: !secret person_1
        state: 'home'
      - condition: not
        conditions:
          - condition: state
            entity_id: switch.sonoff_s20_desk_relay
            state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.sonoff_s20_desk_relay

- alias: Turn off desk plug
  id: '1597432590'
  trigger:
    - platform: time
      at: '19:00:00'
    - platform: state
      entity_id: !secret device3
      to: 'not_home'
      for: '00:30:00'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.sonoff_s20_desk_relay
        state: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.sonoff_s20_desk_relay
