---
# plant automations

- id: '1566533531'
  alias: Plant care water
  trigger:
    - platform: numeric_state
      entity_id: sensor.yucca_aloifolia_moisture
      below: 15
    - platform: numeric_state
      entity_id: sensor.howea_forsteriana_moisture
      below: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret person_1
        state: 'home'
        for:
          minutes: 20
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
  action:
    - service: !secret notify_ios
      data_template:
        message: '{{ trigger.to_state.name }}: {{ trigger.to_state.state }}. Bitte gießen.'
- id: '1566533532'
  alias: Plant Care fertilizer
  trigger:
    - platform: numeric_state
      entity_id: sensor.yucca_aloifolia_soil_conductivity
      below: 350
    - platform: numeric_state
      entity_id: sensor.howea_forsteriana_soil_conductivity
      below: 350
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret person_1
        state: 'home'
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
  action:
    - service: !secret notify_ios
      data_template:
        message: '{{ trigger.to_state.name }}: {{ trigger.to_state.state }}. Bitte düngen.'
