---
# presence automations

- alias: left home person 1
  id: '1515583360'
  trigger:
    - platform: state
      entity_id: !secret person_1
      from: home
      to: not_home
      for:
        minutes: 5
    - platform: tag
      tag_id: aff22e09-b9ba-4925-9170-0c6a7d614184
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - media_player.sony_bravia_tv
          - media_player.playstation_4
          - light.bedroom
          - light.silicon_labs_ezsp_bathroom_lights
          - light.kuche
          - light.hall
          - light.tradfri_gu10_light
          - light.living_room
          - input_boolean.loop_livingcolors_1
          - input_boolean.loop_livingcolors_2

- id: '1553547958'
  alias: Turn off magic mirror
  trigger:
    - platform: state
      entity_id: binary_sensor.is_home
      from: 'on'
      to: 'off'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.magic_mirror

- id: '1553548399'
  alias: Turn on magic mirror
  trigger:
    - platform: state
      entity_id: binary_sensor.is_home
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.raspberry_pi
    state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.magic_mirror

- alias: Lights and TV off
  id: '1553548400'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.time_turnoff_devices', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - media_player.sony_bravia_tv
          - media_player.playstation_4
          - light.bedroom
          - light.silicon_labs_ezsp_bathroom_lights
          - light.kuche
          - light.hall
          - light.tradfri_gu10_light
          - light.living_room
