---

- alias: left home device1
  id: '1515583360'
  trigger:
    - platform: state
      entity_id: !secret person_1
      from: home
      to: not_home
      for:
        minutes: 5
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - media_player.braviatv_1
          - media_player.playstation_4
          - light.schlafzimmer
          - light.badezimmer
          - light.kuche
          - light.vorzimmer
          - light.toilette
          - light.wohnzimmer
          - input_boolean.loop_livingcolors_1
          - input_boolean.loop_livingcolors_2

- id: '1553547958'
  alias: Turn off magic mirror
  trigger:
    - platform: state
      entity_id: sensor.is_home
      from: 'true'
      to: 'false'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.magic_mirror

- id: '1553548399'
  alias: Turn on magic mirror
  trigger:
    - platform: state
      entity_id: !secret person_1
      to: home
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.magic_mirror

- alias: Lights and TV off
  id: '1553548400'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == (states.input_datetime.time_turnoff_devices.attributes.timestamp
      | int | timestamp_custom("%H:%M", False)) }}'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - media_player.braviatv_1
          - media_player.playstation_4
          - light.schlafzimmer
          - light.badezimmer
          - light.kuche
          - light.vorzimmer
          - light.toilette
          - light.wohnzimmer
