# - alias: update available tasmota sonoff 3082
#   id: '111999111'
#   trigger:
#     platform: time
#     at: 09:15:00
#   condition:
#     condition: template
#     value_template: '{{ states.sensor.sonoff_maddox_version.state | replace("v", "")
#       != states.sensor.sonoff_3028_version.state[:5] }}'
#   action:
#   - service: !secret notify_ios
#     data_template:
#       message: 'Sonoff-Tasmota version {{ states.sensor.sonoff_maddox_version.state
#         | replace("v", "") }} is available. Do you wish to upgrade? Changelog: https://is.gd/tasmota'
#       data:
#         push:
#           category: sonoff_a_update

# - alias: upgrade tasmota sonoff 3082
#   id: '999111999'
#   trigger:
#     platform: event
#     event_type: ios.notification_action_fired
#     event_data:
#       actionName: SONOFF_A_UPGRADE
#   action:
#   - service: script.tasmota_upgrade_sonoff_3082
