---

- alias: update available tasmota sonoff 3463
  id: '1556957332'
  trigger:
    platform: time
    at: 09:15:00
  condition:
    condition: template
    value_template: '{{ states.sensor.sonoff_maddox_version.state | replace("v", "")
      != states.sensor.s20_mm_version.state[:5] }}'
  action:
    - service: !secret notify_ios
      data_template:
        message: 'Sonoff-Tasmota version {{ states.sensor.sonoff_maddox_version.state | replace("v", "") }} is available. Do you wish to upgrade? Changelog: https://is.gd/tasmota'
        data:
          push:
            category: sonoff_b_update

- alias: upgrade tasmota sonoff 3463
  id: '1556957333'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SONOFF_B_UPGRADE
  action:
    - service: script.tasmota_upgrade_sonoff_3463
