---
# system automations

- alias: Startup Theme
  id: '1500779867'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: soft_ui

- alias: Update notifications
  id: '1500779868'
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: !secret notify_ios
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."

- alias: SSL expiry notification
  id: '1500779870'
  trigger:
    platform: template
    value_template: "{{ 0 < ( ( as_timestamp(states('sensor.cert_expiry_timestamp_stauber_io'), default=0) - as_timestamp(now(), default=0) ) | float(default=0) / 86400 ) | round(0) <= 21 }}"
  action:
    service: !secret notify_ios
    data_template:
      message: "Warning - SSL certificate expires in {{ ( ( as_timestamp(states('sensor.cert_expiry_timestamp_stauber_io'), default=0) - as_timestamp(now(), default=0) ) | float(default=0) / 86400 ) | round(0) }} days and has not been automatically renewed."

- alias: Disk Use Alarm
  id: '1500589867'
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use
      above: 90
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_lv0
      above: 90
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_lv1
      above: 90
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_sda1
      above: 90
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_sdb1
      above: 90
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_sdb2
      above: 95
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_sdb3
      above: 95
  action:
    service: !secret notify_ios
    data_template:
      message: "Your harddrive is running out of space - {{ state_attr(trigger.entity_id, 'friendly_name') }}: {{ states(trigger.entity_id) }}%"

- alias: Log Level
  id: '1500589870'
  trigger:
    platform: state
    entity_id: input_select.log_level
  condition:
    condition: template
    value_template: "{{ states('input_select.log_level') != 'none' }}"
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: '{{ trigger.to_state.state }}'

- alias: HACS pending update notification
  id: '1577405128'
  trigger:
    platform: state
    entity_id: sensor.hacs
  condition:
    - condition: template
      value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
    - condition: template
      value_template: "{{ (states(trigger.entity_id) | float(default=0)) != 0}}"
  action:
    service: persistent_notification.create
    data_template:
      title: Updates pending in HACS
      message: >-
        {% for repo in state_attr(trigger.entity_id, 'repositories') %}
          **{{ repo.display_name }}** _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
        {% endfor %}
