---
# vacuum automations

- id: '1555971390'
  alias: robovac auto turn on
  trigger:
    - platform: time_pattern
      minutes: '/30'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: counter.vacuum_counter
        below: 2
      - condition: state
        entity_id: sensor.is_home
        state: 'false'
        for:
          minutes: 20
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.vacuum_weekends
            state: 'on'
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: 'on'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ state_attr('vacuum.robovac', 'battery_level') == 100 }}"
              - condition: numeric_state
                entity_id: counter.vacuum_counter
                below: 2
              - condition: template
                value_template: "{{ states('sensor.time') >= states('input_datetime.vacuum_schedule_1_from') }}"
              - condition: template
                value_template: "{{ states('sensor.time') <= states('input_datetime.vacuum_schedule_1_to') }}"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ state_attr('vacuum.robovac', 'battery_level') > 85 }}"
              - condition: state
                entity_id: counter.vacuum_counter
                state: '1'
              - condition: template
                value_template: "{{ states('sensor.time') >= states('input_datetime.vacuum_schedule_2_from') }}"
              - condition: template
                value_template: "{{ states('sensor.time') <= states('input_datetime.vacuum_schedule_2_to') }}"
  action:
    - service: vacuum.turn_on
      data:
        entity_id: vacuum.robovac

- id: '1555971391'
  alias: robovac clean counter
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('vacuum.robovac', 'status', 'cleaning') }}"
  action:
    - service: counter.increment
      data:
        entity_id: counter.vacuum_counter

- id: '1555975479'
  alias: robovac clean notification
  trigger:
    - platform: time_pattern
      hours: '/2'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: !secret person_1
        state: 'home'
        for:
          minutes: 20
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
      - condition: numeric_state
        entity_id: counter.vacuum_counter
        above: 0
      - condition: template
        value_template: "{{ states('vacuum.robovac') != 'on' }}"
  action:
    - service: !secret notify_ios
      data_template:
        message: "Schurli ist zu entleeren. Anzahl der Saugvorgänge: {{ states('counter.vacuum_counter') }}"
        data:
          push:
            category: emptyrobovac

- alias: robovac cleaned
  id: '1555975480'
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: EMPTY_ROBOVAC_NOW
    - platform: event
      event_type: deconz_event
      event_data:
        unique_id: 00:15:8d:00:04:23:f2:45
        event: 1002
  condition:
    condition: state
    entity_id: !secret person_1
    state: 'home'
  action:
    - service: counter.reset
      data:
        entity_id: counter.vacuum_counter
