---
# wemos automations

- alias: update available tasmota wemosd1 1
  id: '1556957334'
  trigger:
    platform: time
    at: 09:15:00
  condition:
    condition: template
    value_template: '{{ states.sensor.sonoff_maddox_version.state | replace("v", "") != states.sensor.wemosd1_version.state[:5] }}'
  action:
    - service: !secret notify_ios
      data_template:
        message: 'Sonoff-Tasmota version {{ states.sensor.sonoff_maddox_version.state | replace("v", "") }} is available. Do you wish to upgrade? Changelog: https://is.gd/tasmota'
        data:
          push:
            category: wemos_a_update

- alias: upgrade tasmota wemosd1 1
  id: '1556957335'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: WEMOS_A_UPGRADE
  action:
    - service: script.tasmota_upgrade_wemosd1_1
