---
# my home assistant configuration

homeassistant:
  name: Home
  latitude: !secret hass_config_lat
  longitude: !secret hass_config_long
  country: !secret country
  elevation: 158
  unit_system: metric
  time_zone: !secret hass_tz
  customize: !include_dir_merge_named customization/customize/
  customize_domain: !include customization/customize_domain.yaml
  customize_glob: !include customization/customize_global.yaml
  auth_providers:
    - type: homeassistant

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret proxy_ip

# default config
automation: !include_dir_merge_list automation/
backup:
config:
conversation:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
history:
logbook:
logger:
  default: error
  logs:
    homeassistant.components.http.ban: warning
    # homeassistant.components.homekit: debug
    # pyhap: debug
    # pydeconz: debug
    # homeassistant.components.deconz: debug
  filters:
    homeassistant.components.shell_command:
      - '^Error running command\:.*ssh.*sudo shutdown -h now.*return code: 255$'
lovelace: !include lovelace/lovelace.yaml
map:
mobile_app:
my:
network:
recorder:
  db_url: !secret mysql_db
  purge_keep_days: 30
  include: !include integrations/recorder_include.yaml
  exclude: !include integrations/recorder_exclude.yaml
scene: !include integrations/scenes.yaml
script: !include_dir_merge_named script/
sun:
system_health:
zeroconf:

### one liners
binary_sensor: !include integrations/binary_sensor.yaml
counter: !include integrations/counter.yaml
cover: !include integrations/cover.yaml
group: !include integrations/groups.yaml
homekit: !include integrations/homekit.yaml
input_boolean: !include integrations/input_boolean.yaml
input_datetime: !include integrations/input_datetime.yaml
input_number: !include integrations/input_number.yaml
input_select: !include integrations/input_select.yaml
media_player: !include integrations/media_player.yaml
notify: !include integrations/notify.yaml
plant: !include integrations/plant.yaml
sensor: !include_dir_merge_list integrations/sensor/
shell_command: !include integrations/shell_command.yaml
switch: !include integrations/switch.yaml
template: !include integrations/template.yaml
zone: !include integrations/zone.yaml

### other components

mqtt:
  sensor: !include integrations/mqtt_sensors.yaml

owntracks:
  max_gps_accuracy: 200
  new_device_defaults:
    track_new_devices: false

sonos:
  media_player:
    advertise_addr: !secret host_ip

panel_iframe:
  valetudo:
    title: 'Valetudo'
    url: !secret valetudo_url
    icon: mdi:robot-vacuum

zha:
  zigpy_config:
    ota:
      ikea_provider: true
      otau_directory: /mnt/zha-otau
