---

title: Home

custom_header:
  compact_mode: true
  # background: var(--app-header-background-color);
  # hide_header: true
  voice_hide: true
  hide_config: true
  hidden_tab_redirect: false
  elements_color: var(--primary-text-color);
  tab_indicator_color: var(--primary-text-color);
  hide_tabs:
    - plants
    - settings

x-vacuum-buttons: &vacuum-buttons
  color: auto
  entity: vacuum.robovac
  size: 25%

# background: center / cover repeat-y url("/local/background/dark-wp.jpg") fixed

excluded_entities: !include /config/lovelace/excluded-entities.yaml

views: !include_dir_merge_list lovelace/views/
