---

input_boolean.vacuum_weekends:
  friendly_name: Wochenenden
input_boolean.wakeup_weekends:
  friendly_name: Wochenenden
input_select.log_level:
  icon: mdi:note-text
input_select.hue_scenes:
  friendly_name: hue Szene
  icon: mdi:spotlight
