---
# sensor customization

sensor.asuswrt_download:
  unit_of_measurement: GB
sensor.asuswrt_upload:
  unit_of_measurement: GB
sensor.count_automations:
  friendly_name: Automations
  icon: mdi:play-circle
sensor.count_scripts:
  friendly_name: Scripts
  icon: mdi:file-document
sensor.cpu_speed:
  friendly_name: CPU Frequenz
sensor.cpu_temperature:
  friendly_name: CPU Temperatur
sensor.database_size_hass:
  friendly_name: Datenbankgröße HA
  icon: mdi:database
sensor.database_size_nc:
  friendly_name: Datenbankgröße NC
  icon: mdi:database
sensor.disk_use_percent_lv:
  friendly_name: '/dev/lv'
  icon: mdi:harddisk
sensor.disk_use_percent_lv0:
  friendly_name: '/dev/lv0'
  icon: mdi:harddisk
sensor.disk_use_percent_lv1:
  friendly_name: '/dev/lv1'
  icon: mdi:harddisk
sensor.disk_use_percent_sdb1:
  friendly_name: '/dev/sdb1'
  icon: mdi:harddisk
sensor.disk_use_percent_sdb2:
  friendly_name: '/dev/sdb2'
  icon: mdi:harddisk
sensor.disk_use_percent_sda1:
  friendly_name: '/dev/sda1'
  icon: mdi:harddisk
sensor.google_travel_time_dev1_dynamic_home:
  friendly_name: Heimweg - dynamisch
  icon: mdi:google-circles-extended
sensor.google_travel_time_dev1_transit:
  friendly_name: Arbeitsweg - Öffis
  icon: mdi:train
sensor.hass_version:
  friendly_name: HA-Version
sensor.howea_forsteriana_moisture:
  friendly_name: Kentia - Feuchtigkeit
sensor.howea_forsteriana_soil_conductivity:
  friendly_name: Kentia - Leitfähigkeit
sensor.memory_use_percent:
  friendly_name: RAM
  icon: mdi:memory
sensor.network_in_eth0:
  friendly_name: Download
  icon: mdi:download-network
sensor.network_out_eth0:
  friendly_name: Upload
  icon: mdi:upload-network
sensor.processor_use:
  friendly_name: CPU
  icon: mdi:desktop-classic
sensor.speedtest_download:
  friendly_name: Download
  icon: mdi:download
sensor.speedtest_ping:
  friendly_name: Ping
  icon: mdi:webpack
sensor.speedtest_upload:
  friendly_name: Upload
  icon: mdi:upload
sensor.swap_use_percent:
  friendly_name: Swap
sensor.uberx_time:
  friendly_name: uberX - Fahrtzeit
  icon: mdi:uber
sensor.uberx_price:
  friendly_name: uberX - Preis
  icon: mdi:uber
sensor.uptime:
  friendly_name: HA Betriebszeit
  icon: mdi:arrow-up-thick
sensor.living_room_humidity:
  friendly_name: Luftfeuchtigkeit - Zimmer
sensor.living_room_temperature:
  friendly_name: Temperatur - Zimmer
sensor.yucca_aloifolia_moisture:
  friendly_name: Yucca - Feuchtigkeit
sensor.yucca_aloifolia_soil_conductivity:
  friendly_name: Yucca - Leitfähigkeit
