sensor.asuswrt_download:
  unit_of_measurement: GB
sensor.asuswrt_upload:
  unit_of_measurement: GB
sensor.count_automations:
  friendly_name: Automations
  icon: mdi:play-circle
sensor.count_scripts:
  friendly_name: Scripts
  icon: mdi:file-document
sensor.cpu_speed:
  friendly_name: CPU Frequenz
sensor.cpu_temperature:
  friendly_name: CPU Temperatur
sensor.database_size_hass:
  friendly_name: Datenbankgröße HA
  icon: mdi:database
sensor.database_size_nc:
  friendly_name: Datenbankgröße NC
  icon: mdi:database
sensor.disk_free:
  friendly_name: SSD
sensor.disk_use_percent:
  friendly_name: SSD
sensor.fail2ban_homeassistant:
  friendly_name: homeassistant
  icon: mdi:shield
sensor.fail2ban_nextcloud:
  friendly_name: nextcloud
  icon: mdi:shield
sensor.fail2ban_sshd:
  friendly_name: sshd
  icon: mdi:shield
sensor.google_travel_time_dev1_dynamic_home:
  friendly_name: Heimweg - dynamisch
  icon: mdi:google-circles-extended
sensor.google_travel_time_dev1_transit:
  friendly_name: Arbeitsweg - Öffis
  icon: mdi:train
sensor.hass_version:
  friendly_name: HA-Version
sensor.howeaforsteriana_moisture:
  friendly_name: Kentia - Feuchtigkeit
sensor.howeaforsteriana_conductivity:
  friendly_name: Kentia - Leitfähigkeit
sensor.howeaforsteriana_battery:
  friendly_name: Kentia - Batterie
sensor.memory_use_percent:
  friendly_name: RAM
  icon: mdi:memory
sensor.network_in_eth0:
  friendly_name: Download
  icon: mdi:download-network
sensor.network_out_eth0:
  friendly_name: Upload
  icon: mdi:upload-network
sensor.processor_use:
  friendly_name: CPU
  icon: mdi:desktop-classic
# sensor.sonoff_3028_version:
#  friendly_name: Tasmota Version
# sensor.sonoff_office_humidity:
#  friendly_name: Luftfeuchtigkeit - Büro
#  icon: mdi:water-percent
#  homebridge_hidden: false
# sensor.sonoff_office_temperature:
#  friendly_name: Temperatur - Büro
#  homebridge_hidden: false
# sensor.sonoff_rssi:
#  friendly_name: Signalstärke
#  icon: mdi:signal-variant
# sensor.sonoff_uptime:
#  friendly_name: Betriebszeit
#  icon: mdi:arrow-up-thick
# sensor.sonoff_vcc:
#  friendly_name: Versorgungsspannung
#  icon: mdi:flash
sensor.speedtest_download:
  friendly_name: Download
  icon: mdi:download
sensor.speedtest_ping:
  friendly_name: Ping
  icon: mdi:webpack
sensor.speedtest_upload:
  friendly_name: Upload
  icon: mdi:upload
sensor.swap_use_percent:
  friendly_name: Swap
sensor.uberx_time:
  friendly_name: uberX - Fahrtzeit
  icon: mdi:uber
sensor.uberx_price:
  friendly_name: uberX - Preis
  icon: mdi:uber
sensor.uptime:
  friendly_name: HA Betriebszeit
  icon: mdi:arrow-up-thick
sensor.wemosd1_room_humidity:
  friendly_name: Luftfeuchtigkeit - Zimmer
  icon: mdi:water-percent
sensor.wemosd1_room_temperature:
  friendly_name: Temperatur - Zimmer
sensor.yuccaelephantipes_moisture:
  friendly_name: Yucca - Feuchtigkeit
sensor.yuccaelephantipes_conductivity:
  friendly_name: Yucca - Leitfähigkeit
sensor.yuccaelephantipes_battery:
  friendly_name: Yucca - Batterie
