---
# global customization

"cover.fyrtur_*":
  device_class: blind
"input_boolean.loop_livingcolors_*":
  friendly_name: Loop-Effekt
  icon: mdi:spotlight
"script.scene_*":
  icon: mdi:spotlight
"zone.*":
  track_ios: false
"sensor.*temperature*":
  device_class: temperature
"sensor.*humidity*":
  device_class: humidity
"sensor.fail2ban_*":
  icon: mdi:shield
"light.silicon_labs_ezsp_*":
  is_zha_group: true
