---
# global customization

"cover.fyrtur_*":
  device_class: blind
"input_boolean.loop_livingcolors_*":
  friendly_name: Loop-Effekt
  icon: mdi:spotlight
"script.scene_*":
  icon: mdi:spotlight
"zone.*home":
  friendly_name: home
"zone.*":
  track_ios: false
"sensor.*temperature*":
  device_class: temperature
"sensor.*humidity*":
  device_class: humidity
