---
# Blinds view

- title: Blinds
  path: blinds
  icon: mdi:window-closed
  cards:
    - type: vertical-stack  # left column
      cards:
        - type: markdown  ### blinds living room
          content: |
            # Living room
            {% set entities = 'cover.fyrtur_1', 'cover.fyrtur_2' %}
            {% if (states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','==',0) | list | length) == 2 %}
              ## All blinds are closed
            {% elif (states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','==',100) | list | length) != 2 %}
              ## The blinds are partially closed
            {% elif (states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','==',100) | list | length) == 2 %}
              ## All blinds are open
            {% endif %}
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: vertical-stack  ### Living room buttons
          cards:
            - type: horizontal-stack
              cards:
                - type: 'custom:button-card'  # group
                  entity: cover.living_room_group
                  icon: mdi:sofa
                  show_icon: true
                  show_name: false
                  state:
                    - styles:
                        card:
                          - box-shadow: var(--softui-onoffbutton-active-boxshadow)
                      value: 'open'
                  card_mod:
                    class: soft-ui
                  styles:
                    card:
                      - width: 80px
                      - height: 80px
                    icon:
                      - color: var(--primary-text-color)
                  tap_action:
                    action: toggle
                  double_tap_action:
                    action: call-service
                    service: cover.stop_cover
                    service_data:
                      entity_id: cover.living_room_group
                  hold_action:
                    action: more-info
                - type: 'custom:button-card'  # fyrtur 1
                  entity: cover.fyrtur_1
                  show_icon: true
                  show_name: false
                  state:
                    - styles:
                        card:
                          - box-shadow: var(--softui-onoffbutton-active-boxshadow)
                      value: 'open'
                  card_mod:
                    class: soft-ui
                  styles:
                    card:
                      - width: 80px
                      - height: 80px
                    icon:
                      - color: >
                          [[[
                            if (states['binary_sensor.window_openclose_1'].state == 'on') return 'var(--paper-item-icon-active-color)';
                            else return 'var(--primary-text-color)';
                          ]]]
                  tap_action:
                    action: toggle
                  double_tap_action:
                    action: call-service
                    service: cover.stop_cover
                    service_data:
                      entity_id: cover.fyrtur_1
                  hold_action:
                    action: more-info
                - type: 'custom:button-card'  # fyrtur 2
                  entity: cover.fyrtur_2
                  show_icon: true
                  show_name: false
                  state:
                    - styles:
                        card:
                          - box-shadow: var(--softui-onoffbutton-active-boxshadow)
                      value: 'open'
                  card_mod:
                    class: soft-ui
                  styles:
                    card:
                      - width: 80px
                      - height: 80px
                    icon:
                      - color: >
                          [[[
                            if (states['binary_sensor.window_openclose_2'].state == 'on') return 'var(--paper-item-icon-active-color)';
                            else return 'var(--primary-text-color)';
                          ]]]
                  tap_action:
                    action: toggle
                  double_tap_action:
                    action: call-service
                    service: cover.stop_cover
                    service_data:
                      entity_id: cover.fyrtur_2
                  hold_action:
                    action: more-info
        - type: markdown  ### blinds bed room
          content: |
            # Bed room
            {% set entities = 'cover.shellyplus2pm_b8d61a89016c' %}
            {% if (states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','==',0) | list | length) == 1 %}
              ## All blinds are closed
            {% elif (states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','==',100) | list | length) != 1 %}
              ## The blinds are partially closed
            {% elif (states | selectattr('entity_id','in', entities) | selectattr('attributes.current_position','==',100) | list | length) == 1 %}
              ## All blinds are open
            {% endif %}
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: 'custom:button-card'  # group
          entity: cover.shellyplus2pm_b8d61a89016c
          icon: mdi:bed-empty
          show_icon: true
          show_name: false
          state:
            - styles:
                icon:
                  - color: var(--paper-item-icon-active-color)
                card:
                  - box-shadow: var(--softui-onoffbutton-active-boxshadow)
              value: 'open'
          card_mod:
            class: soft-ui
          styles:
            card:
              - width: 80px
              - height: 80px
            icon:
              - color: var(--primary-text-color)
          tap_action:
            action: toggle
          double_tap_action:
            action: call-service
            service: cover.stop_cover
            service_data:
              entity_id: cover.shellyplus2pm_b8d61a89016c
          hold_action:
            action: more-info
        - type: markdown  ### column
          content: |
            # Settings
            ## Various settings
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.wakeup_open_time_covers
              name: Blind opening time
              icon: mdi:clock
            - entity: input_number.wakeup_cover_open_delay
              name: Delay
            - entity: input_datetime.time_close_covers_night
              name: Blind closing time
          card_mod:
            class: soft-ui
