---
# Server view

- icon: mdi:server
  title: Server
  cards:
    - type: vertical-stack  # left column
      cards:
        - type: markdown  ### column
          content: |
            # Server
            ## Basic server information
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: entities
          # title: Informationen
          show_header_toggle: false
          entities:
            - entity: sensor.last_boot
              name: Server Uptime
              format: relative
            - entity: sensor.uptime
              name: Home-Assistant Uptime
            - entity: sensor.cert_expiry_timestamp_stauber_io
              name: Cert expiry
              icon: mdi:certificate
          card_mod:
            class: soft-ui-standard
        - type: horizontal-stack
          cards:
            - type: custom:mini-graph-card
              name: Frequency
              points_per_hour: 2
              line_color: '#1c6bba'
              font_size: 55
              font_size_header: 12
              card_mod:
                class: soft-ui-standard
              entities:
                - sensor.cpu_speed
            - type: custom:mini-graph-card
              name: Load
              points_per_hour: 12
              font_size: 55
              font_size_header: 12
              # show:
              #   fill: false
              hours_to_show: 6
              line_color:
                - red
                - blue
                - green
              card_mod:
                class: soft-ui-standard
              entities:
                - entity: sensor.load_1m
                  name: 1m
                - entity: sensor.load_5m
                  name: 5m
                - entity: sensor.load_15m
                  name: 15m
        - type: horizontal-stack
          cards:
            - type: custom:gauge-card
              entity: sensor.cpu_temperature
              title: CPU Temp
              min: 0
              max: 100
              scale: 25px
              severity:
                red: 80
                green: 0
                amber: 45
              card_mod:
                class: soft-ui-standard
              style: |
                  .gauge-a {
                    background-color: var(--ha-card-background);
                  }
                  .gauge-b {
                    background-color: var(--primary-background-color);
                  }
            - type: custom:gauge-card
              entity: sensor.processor_use
              title: CPU
              min: 0
              max: 100
              scale: 25px
              severity:
                red: 80
                green: 0
                amber: 45
              card_mod:
                class: soft-ui-standard
                style: |
                  .gauge-a {
                    background-color: var(--ha-card-background);
                  }
                  .gauge-b {
                    background-color: var(--primary-background-color);
                  }
            - type: custom:gauge-card
              entity: sensor.memory_use_percent
              title: RAM
              min: 0
              max: 100
              scale: 25px
              severity:
                red: 80
                green: 0
                amber: 45
              card_mod:
                class: soft-ui-standard
                style: |
                  .gauge-a {
                    background-color: var(--ha-card-background);
                  }
                  .gauge-b {
                    background-color: var(--primary-background-color);
                  }
        - type: custom:bar-card
          entities:
            - entity: sensor.disk_use_percent_lv
              name: lv - /
            - entity: sensor.disk_use_percent_lv0
              name: lv - /home
            - entity: sensor.disk_use_percent_lv1
              name: lv - /srv
            - entity: sensor.disk_use_percent_sda1
            - entity: sensor.disk_use_percent_sdb1
            - entity: sensor.disk_use_percent_sdb2
            - entity: sensor.disk_use_percent_sdb3
          height: 22px
          width: 70%
          severity:
            - color: green
              from: 0
              to: 60
            - color: orange
              from: 61
              to: 90
            - color: red
              from: 91
              to: 100
          positions:
            name: outside
            indicator: inside
          card_mod:
            class: soft-ui-standard
            style: |
              bar-card-value {
                  margin: auto;
                  font-size: 12px;
              }
              bar-card-row {
                  height: 24px;
              }
              bar-card-currentbar, bar-card-backgroundbar {
                  border-radius: 4px;
              }
              bar-card-indicator {
                  left: 3px;
              }
    - type: vertical-stack  # middle column
      cards:
        - type: markdown  ### column
          content: |
            # Database
            ## Sizes of the database server
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: glance
          entities:
            - entity: sensor.database_size_hass
              name: Home-Assistant
              format: relative
            - entity: sensor.database_size_nc
              name: Nextcloud
          card_mod:
            class: soft-ui-standard
        - type: markdown  ### column
          content: |
            # Network
            ## Information and statistics
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.dns_lookup
              name: Public IP
              icon: mdi:wan
          card_mod:
            class: soft-ui-standard
    - type: vertical-stack  # right column
      cards:
        - type: markdown  ### column
          content: |
            # Fail2Ban
            ## IP bans
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: glance
          columns: 4
          entities:
            - entity: !secret f2b_jail1_sensor
              name: !secret f2b_jail1_sensor_name
            - entity: !secret f2b_jail2_sensor
              name: !secret f2b_jail2_sensor_name
            - entity: !secret f2b_jail3_sensor
              name: !secret f2b_jail3_sensor_name
            - entity: !secret f2b_jail4_sensor
              name: !secret f2b_jail4_sensor_name
            - entity: !secret f2b_jail5_sensor
              name: !secret f2b_jail5_sensor_name
          card_mod:
            class: soft-ui-standard
        - type: markdown  ### column
          content: |
            # Home-Assistant
            ## Statistics and information
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: custom:stack-in-card
          card_mod:
            class: soft-ui-standard
          mode: vertical
          cards:
            - type: glance
              columns: 8
              show_name: false
              entities:
                - entity: sensor.count_automations
                  name: Automations
                  icon: mdi:play-circle
                - entity: sensor.count_binary_sensors
                  name: Binary Sensors
                  icon: mdi:transition-masked
                - entity: sensor.count_lights
                  name: Lights
                  icon: mdi:lightbulb
                - entity: sensor.count_covers
                  name: Covers
                  icon: mdi:blinds
                - entity: sensor.count_scripts
                  name: Scripts
                  icon: mdi:script-text
                - entity: sensor.count_sensors
                  name: Sensors
                  icon: mdi:counter
                - entity: sensor.count_switches
                  name: Switches
                  icon: mdi:toggle-switch
                - entity: sensor.count_zones
                  name: Zones
                  icon: mdi:crosshairs-gps
            - type: entities
              show_header_toggle: false
              entities:
                - entity: input_select.log_level
