---
# Device view

- icon: mdi:chip
  title: IoT
  path: iot
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            ### Magic Mirror
          style: |
            ha-card {
              height: 50px;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 20px;
              font-weight: bold;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 10px
            - type: custom:stack-in-card
              mode: vertical
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow: var(--softui-standard-boxshadow);
                }
              cards:
                - type: entities
                  show_header_toggle: false
                  entities:
                    - entity: switch.magic_mirror
                      name: Magic Mirror
                    - entity: switch.sonoff_s20_magicmirror_relay
                      name: S20 - Magic Mirror
                - type: glance
                  # title: S20 - MM
                  entities:
                    - entity: sensor.sonoffs20_magicmirror_version
                      name: Version
                      icon: mdi:alpha-v-box
                    - entity: sensor.sonoffs20_magicmirror_ip_address
                      name: IP
                      icon: mdi:map-marker
                    - entity: sensor.sonoffs20_magicmirror_uptime
                      name: Uptime
                      icon: mdi:arrow-up-thick
                    - entity: sensor.sonoffs20_magicmirror_wifi_signal_sensor
                      name: RSSI
                      icon: mdi:signal-variant
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 10px
        - type: markdown
          content: |
            ### Desk outlet
          style: |
            ha-card {
              height: 50px;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 20px;
              font-weight: bold;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 10px
            - type: custom:stack-in-card
              mode: vertical
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow: var(--softui-standard-boxshadow);
                }
              cards:
                - type: entities
                  show_header_toggle: false
                  entities:
                    - entity: switch.sonoff_s20_desk_relay
                      name: S20 - desk outlet
                - type: glance
                  # title: S20 - desk
                  entities:
                    - entity: sensor.sonoffs20_desk_version
                      name: Version
                      icon: mdi:alpha-v-box
                    - entity: sensor.sonoffs20_desk_ip_address
                      name: IP
                      icon: mdi:map-marker
                    - entity: sensor.sonoffs20_desk_uptime
                      name: Uptime
                      icon: mdi:arrow-up-thick
                    - entity: sensor.sonoffs20_desk_wifi_signal_sensor
                      name: RSSI
                      icon: mdi:signal-variant
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 10px
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            ### ESP32 - living room
          style: |
            ha-card {
              height: 50px;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 20px;
              font-weight: bold;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
            - type: custom:stack-in-card
              mode: vertical
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow: var(--softui-standard-boxshadow);
                }
              cards:
                - type: glance
                  # title: wemosd1 - 1
                  entities:
                    - entity: sensor.esp32_living_room_version
                      name: Version
                      icon: mdi:alpha-v-box
                    - entity: sensor.esp32_living_room_ip_address
                      name: IP
                      icon: mdi:map-marker
                    - entity: sensor.esp32_living_room_uptime
                      name: Uptime
                      icon: mdi:arrow-up-thick
                    - entity: sensor.esp32_living_room_wifi_signal_sensor
                      name: RSSI
                      icon: mdi:signal-variant
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
        - type: 'custom:button-card'  # Spacer
          show_icon: false
          show_name: false
          style: |
            ha-card {
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
            }
          styles:
            card:
              - width: 5px
              - height: 10px
