---
# Plants view

- icon: mdi:sprout
  title: Plants
  subview: true
  path: plants
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # Plants
            ## My poor plants. May the light be with them.
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: horizontal-stack  # kentia
          cards:
            - type: plant-status
              entity: plant.howea_forsteriana
              card_mod:
                class: soft-ui
        - type: horizontal-stack  # yucca
          cards:
            - type: plant-status
              entity: plant.yucca_aloifolia
              card_mod:
                class: soft-ui
