---
# Plants view

- icon: mdi:sprout
  title: plants
  visible: false
  path: plants
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            ### Plants
          style: |
            ha-card {
              height: 20px !important;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 20px;
              font-weight: bold;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        - type: markdown
          content: |
            **My poor plants. May the light be with them.**
          style: |
            ha-card {
              height: 50px;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 14px;
              font-weight: thin;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        # - type: horizontal-stack # kentia
        #   cards:
        #     - type: 'custom:button-card'
        #       show_icon: false
        #       show_name: false
        #       style: |
        #         ha-card {
        #         --ha-card-background: 'rgba(11, 11, 11, 0.00)';
        #         box-shadow: 2px 2px rgba(0,0,0,0.0);
        #         }
        #       styles:
        #         card:
        #           - width: 5px
        #           - height: 60px
        #     - type: plant-status
        #       entity: plant.howea_forsteriana
        #       style: |
        #         ha-card {
        #           background-color: var(--primary-background-color);
        #           border-radius: 15px;
        #           box-shadow: var(--softui-standard-boxshadow);
        #         }
        #     - type: 'custom:button-card'
        #       show_icon: false
        #       show_name: false
        #       style: |
        #         ha-card {
        #         --ha-card-background: 'rgba(11, 11, 11, 0.00)';
        #         box-shadow: 2px 2px rgba(0,0,0,0.0);
        #         }
        #       styles:
        #         card:
        #           - width: 5px
        #           - height: 60px
        # - type: 'custom:button-card'
        #   show_icon: false
        #   show_name: false
        #   style: |
        #     ha-card {
        #       --ha-card-background: 'rgba(11, 11, 11, 0.00)';
        #       box-shadow: 2px 2px rgba(0,0,0,0.0);
        #     }
        #   styles:
        #     card:
        #       - width: 5px
        #       - height: 10px
        - type: horizontal-stack  # yucca
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
            - type: plant-status
              entity: plant.yucca_aloifolia
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow: var(--softui-standard-boxshadow);
                }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
        - type: 'custom:button-card'
          show_icon: false
          show_name: false
          style: |
            ha-card {
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
            }
          styles:
            card:
              - width: 5px
              - height: 10px
