---
# Settings view

- icon: mdi:alarm
  title: Alarm
  subview: true
  path: alarm
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # Alarm and sleep schedule
            ## Various settings for alarm automations & co.
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: custom:stack-in-card
          mode: vertical
          card_mod:
            class: soft-ui
          # title: Wake up light
          cards:
            - type: entities
              entities:
                - entity: input_boolean.wakeup
                  name: Wake-up light
            - type: conditional
              conditions:
                - entity: input_boolean.wakeup
                  state: 'on'
              card:
                type: entities
                card_mod:
                  style: |
                    ha-card {
                      background-color: var(--primary-background-color);
                      border-radius: 15px;
                      #box-shadow: 0 0 0 0 rgba(255, 255, 255, 0.0);
                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                    }
                entities:
                  - input_datetime.wakeup_alarm_time
                  - input_number.wakeup_duration
                  - entity: input_number.wakeup_target_brightness
                    name: Target brightness
                  - entity: input_boolean.wakeup_weekends
                    name: Weekends
        - type: entities
          # title: Anderes
          show_header_toggle: false
          entities:
            - entity: input_datetime.time_turnoff_devices
              name: Turn-off time living room
          card_mod:
            class: soft-ui
