---
# Settings view

- icon: mdi:alarm
  title: Alarm
  visible: false
  path: alarm
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            ### Alarm and sleep schedule
          style: |
            ha-card {
              height: 20px;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 20px;
              font-weight: bold;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        - type: markdown
          content: |
            **Various settings for alarm automations & co.**
          style: |
            ha-card {
              height: 50px;
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
              font-size: 14px;
              font-weight: thin;
              font-family: Helvetica;
              letter-spacing: '-0.01em';
            }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
            - type: custom:stack-in-card
              mode: vertical
              style: |
                ha-card {
                  background-color: var(--primary-background-color);
                  border-radius: 15px;
                  box-shadow: var(--softui-standard-boxshadow);
                }
              # title: Wake up light
              cards:
                - type: entities
                  entities:
                    - entity: input_boolean.wakeup
                      name: Wake-up light
                - type: conditional
                  conditions:
                    - entity: input_boolean.wakeup
                      state: 'on'
                  card:
                    type: entities
                    style: |
                      ha-card {
                        background-color: var(--primary-background-color);
                        border-radius: 15px;
                        #box-shadow: 0 0 0 0 rgba(255, 255, 255, 0.0);
                        box-shadow: 2px 2px rgba(0,0,0,0.0);
                      }
                    entities:
                      - input_datetime.wakeup_alarm_time
                      - input_number.wakeup_duration
                      - entity: input_boolean.wakeup_weekends
                        name: Weekends
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
        - type: 'custom:button-card'
          show_icon: false
          show_name: false
          style: |
            ha-card {
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
            }
          styles:
            card:
              - width: 5px
              - height: 10px
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
            - type: entities
              # title: Anderes
              show_header_toggle: false
              entities:
                - entity: input_datetime.time_turnoff_devices
                  name: Turn-off time living room
              style: |
                ha-card {
                  --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                  border-radius: 15px;
                  box-shadow: var(--softui-standard-boxshadow);
                }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              style: |
                ha-card {
                --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                box-shadow: 2px 2px rgba(0,0,0,0.0);
                }
              styles:
                card:
                  - width: 5px
                  - height: 60px
        - type: 'custom:button-card'
          show_icon: false
          show_name: false
          style: |
            ha-card {
              --ha-card-background: 'rgba(11, 11, 11, 0.00)';
              box-shadow: 2px 2px rgba(0,0,0,0.0);
            }
          styles:
            card:
              - width: 5px
              - height: 10px
