---
# Vacuum view

- icon: mdi:robot-vacuum
  title: Vacuum
  subview: true
  path: vacuum
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # valetudo_roborock
            ## Controls
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                  height: 70px !important;
                }
              ha-markdown:
                $: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
            - type: custom:stack-in-card
              card_mod:
                style: |
                  ha-card {
                    height: 130px;
                    background-color: var(--primary-background-color);
                    border-radius: 15px;
                    box-shadow: var(--softui-standard-boxshadow);
                  }
              mode: vertical
              cards:
                - type: entities
                  entities:
                    - entity: vacuum.valetudo_roborock
                      type: custom:multiple-entity-row
                      show_state: false
                      entities:
                        - entity: vacuum.valetudo_roborock
                          name: Status
                        - attribute: battery_level
                          name: Battery
                          unit: '%'
                        - entity: counter.vacuum_dustbin
                          name: Count
                  card_mod:
                    style: |
                      ha-card {
                        height: 70px;
                      }
                - type: horizontal-stack
                  cards:
                    - type: custom:button-card
                      color: auto
                      entity: vacuum.valetudo_roborock
                      size: 25%
                      icon: mdi:play
                      show_name: false
                      styles:
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: vacuum.start
                        service_data:
                          entity_id: vacuum.valetudo_roborock
                    - type: custom:button-card
                      color: auto
                      entity: vacuum.valetudo_roborock
                      size: 25%
                      icon: mdi:pause
                      show_name: false
                      styles:
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: vacuum.pause
                        service_data:
                          entity_id: vacuum.valetudo_roborock
                    - type: custom:button-card
                      color: auto
                      entity: vacuum.valetudo_roborock
                      size: 25%
                      icon: mdi:stop
                      show_name: false
                      styles:
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: vacuum.stop
                        service_data:
                          entity_id: vacuum.valetudo_roborock
                    - type: custom:button-card
                      color: auto
                      entity: vacuum.valetudo_roborock
                      size: 25%
                      icon: mdi:broom
                      show_name: false
                      styles:
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: vacuum.clean_spot
                        service_data:
                          entity_id: vacuum.valetudo_roborock
                    - type: custom:button-card
                      color: auto
                      entity: vacuum.valetudo_roborock
                      size: 25%
                      icon: mdi:map-marker
                      show_name: false
                      styles:
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: vacuum.locate
                        service_data:
                          entity_id: vacuum.valetudo_roborock
                    - type: custom:button-card
                      color: auto
                      entity: vacuum.valetudo_roborock
                      size: 25%
                      icon: mdi:home-map-marker
                      show_name: false
                      styles:
                        icon:
                          - color: var(--primary-text-color)
                      tap_action:
                        action: call-service
                        service: vacuum.return_to_base
                        service_data:
                          entity_id: vacuum.valetudo_roborock
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
        - type: markdown
          content: |
            # Map
            ## Room map and last run
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                  height: 70px !important;
                }
              ha-markdown:
                $: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
            - type: 'custom:valetudo-map-card'
              title: ''
              vacuum: valetudo_roborock
              dock_icon: mdi:dots-vertical
              dock_color: '--secondary-text-color'
              card_mod:
                style: |
                  ha-card {
                    height: 230px;
                    --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                    border-radius: 15px;
                    box-shadow: var(--softui-standard-boxshadow);
                  }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # Maintenance
            ## Consumables and usage
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                  height: 70px !important;
                }
              ha-markdown:
                $: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
            - type: entities
              # title: Anderes
              show_header_toggle: false
              entities:
                - entity: sensor.valetudo_roborock_main_brush_hours
                  name: Main brush
                  icon: mdi:progress-wrench
                - entity: sensor.valetudo_roborock_right_side_brush_hours
                  name: Side brush
                  icon: mdi:progress-wrench
                - entity: sensor.valetudo_roborock_main_filter_hours
                  name: Filter
                  icon: mdi:progress-wrench
                - entity: sensor.valetudo_roborock_sensor_hours
                  name: Sensor
                  icon: mdi:progress-clock
              card_mod:
                style: |
                  ha-card {
                    --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                    border-radius: 15px;
                    box-shadow: var(--softui-standard-boxshadow);
                  }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
        - type: markdown
          content: |
            # Schedule
            ## cleaning schedule settings
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                  height: 70px !important;
                }
              ha-markdown:
                $: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: horizontal-stack
          cards:
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
            - type: entities
              # title: Anderes
              show_header_toggle: false
              entities:
                - type: custom:multiple-entity-row
                  entity: input_datetime.vacuum_schedule_1_to
                  name: Main schedule
                  entities:
                    - entity: input_datetime.vacuum_schedule_1_from
                      name: false
                - entity: input_boolean.vacuum_weekends
                  name: Vacuum on weekends/holidays
              card_mod:
                style: |
                  ha-card {
                    --ha-card-background: 'rgba(11, 11, 11, 0.00)';
                    border-radius: 15px;
                    box-shadow: var(--softui-standard-boxshadow);
                  }
            - type: 'custom:button-card'
              show_icon: false
              show_name: false
              styles:
                card:
                  - width: 5px
                  - height: 60px
                  - box-shadow: '2px 2px rgba(0,0,0,0.0)'
                  - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
        - type: 'custom:button-card'
          show_icon: false
          show_name: false
          styles:
            card:
              - width: 5px
              - height: 10px
              - box-shadow: '2px 2px rgba(0,0,0,0.0)'
              - --ha-card-background: 'rgba(11, 11, 11, 0.00)'
