---
# Vacuum view

- icon: mdi:robot-vacuum
  title: Vacuum
  subview: true
  path: vacuum
  cards:
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # Roborock
            ## Controls
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: tile
          entity: vacuum.valetudo_roborock
          state_content:
            - state
            - battery_level
          hold_action:
             action: more-info
             entity: counter.vacuum_dustbin
          features:
            - type: "vacuum-commands"
              commands:
                - start_pause
                - stop
                - clean_spot
                - locate
                - return_home
          card_mod:
            class: soft-ui
            style:
              ha-tile-info$: |
                .secondary:after {
                  visibility: visible;
                  content: " ⸱ runs: {{ states('counter.vacuum_dustbin') }}";
                }
        - type: markdown
          content: |
            # Map
            ## Last run: {{(states('sensor.valetudo_roborock_current_statistics_area') | float(default=0) / 10000) | round(2)}} m<sup>2</sup> in {{(states('sensor.valetudo_roborock_current_statistics_time') | float(default=0) / 3600) | round(2) }} hours
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: 'custom:valetudo-map-card'
          title: ''
          vacuum: valetudo_roborock
          dock_icon: mdi:dots-vertical
          dock_color: '--secondary-text-color'
          show_status: false
          show_battery_level: false
          show_start_button: false
          show_pause_button: false
          show_stop_button: false
          show_home_button: false
          show_locate_button: false
          card_mod:
            class: soft-ui
            style: |
              ha-card {
                height: 410px;
              }
    - type: vertical-stack
      cards:
        - type: markdown
          content: |
            # Maintenance
            ## Consumables and usage
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: entities
          # title: Anderes
          show_header_toggle: false
          entities:
            - entity: sensor.valetudo_roborock_main_brush_hours
              name: Main brush
              icon: mdi:progress-wrench
            - entity: sensor.valetudo_roborock_right_side_brush_hours
              name: Side brush
              icon: mdi:progress-wrench
            - entity: sensor.valetudo_roborock_main_filter_hours
              name: Filter
              icon: mdi:progress-wrench
            - entity: sensor.valetudo_roborock_sensor_hours
              name: Sensor
              icon: mdi:progress-clock
          card_mod:
            class: soft-ui
        - type: markdown
          content: |
            # Schedule
            ## cleaning schedule settings
          card_mod:
            style:
              .: |
                ha-card {
                  --ha-card-background: none !important;
                  box-shadow: none !important;
                }
              ha-markdown$: |
                  ha-markdown-element {
                    letter-spacing: 0;
                  }
                  h1 {
                    font-size: 20px !important;
                    margin-block-end: 0.2em !important;
                  }
                  h2 {
                    font-size: 15px !important;
                    margin-block-start: 0.2em !important;
                  }
        - type: entities
          # title: Anderes
          show_header_toggle: false
          entities:
            - type: custom:multiple-entity-row
              entity: input_datetime.vacuum_schedule_1_to
              name: Main schedule
              entities:
                - entity: input_datetime.vacuum_schedule_1_from
                  name: false
            - entity: input_boolean.vacuum_weekends
              name: Vacuum on weekends/holidays
          card_mod:
            class: soft-ui
