- platform: geizhals
  name: ILCE-7M3K
  product_id: 1777813
  description: "Sony Alpha 7 III inkl. Objektiv AF E 28-70mm"
  locale: "AT"
- platform: geizhals
  name: ILCE-7M3
  product_id: 1777806
  description: "Sony Alpha 7 III"
  locale: "AT"