#- platform: mqtt
#  name: sonoff_3028_version
#  state_topic: "sonoff_3082/stat/STATUS2"
#  value_template: "{{ value_json['StatusFWR'].Version[:5] }}"

#- platform: mqtt
#  name: sonoff_office_temperature
#  state_topic: "sonoff_3082/tele/SENSOR"
#  value_template: "{{ value_json['AM2301'].Temperature }}"
#  unit_of_measurement: "°C"

#- platform: mqtt
#  name: sonoff_office_humidty
#  state_topic: "sonoff_3082/tele/SENSOR"
#  value_template: "{{ value_json['AM2301'].Humidity }}"
#  unit_of_measurement: "%"

- platform: mqtt
  name: wemosd1_room_temperature
  state_topic: "wemosd1_1/tele/SENSOR"
  value_template: "{{ value_json['SHT3X-0x45'].Temperature }}"
  unit_of_measurement: "°C"

- platform: mqtt
  name: wemosd1_room_humidty
  state_topic: "wemosd1_1/tele/SENSOR"
  value_template: "{{ value_json['SHT3X-0x45'].Humidity }}"
  unit_of_measurement: "%"

#- platform: mqtt
#  name: sonoff_uptime
#  state_topic: "sonoff_3082/tele/STATE"
#  #value_template: "{{ value_json.Uptime }}"
#  value_template: "{{ ((value_json.Uptime[:1] | int * 24) + (value_json.Uptime[2:4] | int) + (value_json.Uptime[5:7] | int / 60) + (value_json.Uptime[8:10] | int / 60 / 60))|round(2) }}"
#  unit_of_measurement: "hours"

#- platform: mqtt
#  name: sonoff_rssi
#  state_topic: "sonoff_3082/tele/STATE"
#  value_template: "{{ value_json['Wifi'].RSSI }}"
#  unit_of_measurement: "dBm"

#- platform: mqtt
#  name: sonoff_vcc
#  state_topic: "sonoff_3082/tele/STATE"
#  value_template: "{{ value_json.Vcc }}"
#  unit_of_measurement: "V"

- platform: mqtt
  name: s20_mm_uptime
  state_topic: "sonoff_3463/tele/STATE"
  value_template: "{{ value_json.Uptime }}"
  #value_template: "{{ ((value_json.Uptime[:1] | int * 24) + (value_json.Uptime[2:4] | int) + (value_json.Uptime[5:7] | int / 60) + (value_json.Uptime[8:10] | int / 60 / 60))|round(2) }}"
  #unit_of_measurement: "hours"

- platform: mqtt
  name: s20_mm_rssi
  state_topic: "sonoff_3463/tele/STATE"
  value_template: "{{ value_json['Wifi'].RSSI }}"
  unit_of_measurement: "dBm"

# - platform: mqtt
#   name: s20_mm_vcc
#   state_topic: "sonoff_3463/tele/STATE"
#   value_template: "{{ value_json.Vcc }}"
#   unit_of_measurement: "V"

- platform: mqtt
  name: s20_mm_ip
  state_topic: "sonoff_3463/stat/STATUS5"
  value_template: "{{ value_json['StatusNET'].IPAddress }}"

- platform: mqtt
  name: s20_mm_version
  state_topic: "sonoff_3463/stat/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version[:5] }}"

- platform: mqtt
  name: wemosd1_version
  state_topic: "wemosd1_1/stat/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version[:5] }}"

- platform: mqtt
  name: wemosd1_ip
  state_topic: "wemosd1_1/stat/STATUS5"
  value_template: "{{ value_json['StatusNET'].IPAddress }}"

- platform: mqtt
  name: wemosd1_uptime
  state_topic: "wemosd1_1/tele/STATE"
  #value_template: "{{ value_json.Uptime }}"
  value_template: "{{ ((value_json.Uptime[:1] | int * 24) + (value_json.Uptime[2:4] | int) + (value_json.Uptime[5:7] | int / 60) + (value_json.Uptime[8:10] | int / 60 / 60))|round(2) }}"
  unit_of_measurement: "hours"

- platform: mqtt
  name: wemosd1_rssi
  state_topic: "wemosd1_1/tele/STATE"
  value_template: "{{ value_json['Wifi'].RSSI }}"
  unit_of_measurement: "dBm"

# - platform: mqtt
#   name: wemosd1_vcc
#   state_topic: "wemosd1_1/tele/STATE"
#   value_template: "{{ value_json.Vcc }}"
#   unit_of_measurement: "V"

- platform: mqtt
  name: sonoff_maddox_version
  state_topic: "sonoff-version"

- platform: mqtt
  name: yuccaelephantipes_moisture
  state_topic: "miflora/YuccaElephantipes"
  value_template: "{{ value_json.moisture }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: yuccaelephantipes_light
  state_topic: "miflora/YuccaElephantipes"
  value_template: "{{ value_json.light }}"
  unit_of_measurement: "lux"

- platform: mqtt
  name: yuccaelephantipes_temperature
  state_topic: "miflora/YuccaElephantipes"
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: "°C"

- platform: mqtt
  name: yuccaelephantipes_conductivity
  state_topic: "miflora/YuccaElephantipes"
  value_template: "{{ value_json.conductivity }}"
  unit_of_measurement: "µS/cm"

- platform: mqtt
  name: yuccaelephantipes_battery
  state_topic: "miflora/YuccaElephantipes"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: HoweaForsteriana_moisture
  state_topic: "miflora/HoweaForsteriana"
  value_template: "{{ value_json.moisture }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: HoweaForsteriana_light
  state_topic: "miflora/HoweaForsteriana"
  value_template: "{{ value_json.light }}"
  unit_of_measurement: "lux"

- platform: mqtt
  name: HoweaForsteriana_temperature
  state_topic: "miflora/HoweaForsteriana"
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: "°C"

- platform: mqtt
  name: HoweaForsteriana_conductivity
  state_topic: "miflora/HoweaForsteriana"
  value_template: "{{ value_json.conductivity }}"
  unit_of_measurement: "µS/cm"

- platform: mqtt
  name: HoweaForsteriana_battery
  state_topic: "miflora/HoweaForsteriana"
  value_template: "{{ value_json.battery }}"
  unit_of_measurement: "%"