- platform: template
  sensors:
    is_home:
      friendly_name: 'Is someone home?'
      entity_id: !secret person_1
      value_template: !secret template_1
    wakeup_start_time_lights:
      friendly_name: 'Fade-in Startzeit'
      value_template: >
        {% if states.input_datetime.wakeup_alarm_time and states.input_number.wakeup_duration %}
        {% set alarmtime = states.input_datetime.wakeup_alarm_time.state %}
        {% set alarm_hour = alarmtime.split(":")[0] | int %}
        {% set alarm_min = alarmtime.split(":")[1] | int %}
        {% set light_dur = states.input_number.wakeup_duration.state | int %}
        {% set alarm_min_light = alarm_min - light_dur %}
        {% if alarm_min_light  < 0 %}
        {% set alarm_min_light = alarm_min_light + 60 %}
        {% set alarm_hour_light = alarm_hour - 1 %}
        {% if alarm_hour_light < 0 %}{% set alarm_hour_light = 23 %}{% endif %}
        {% if alarm_hour_light < 10 %}0{% endif %}{{ alarm_hour_light}}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% else %}
        {% if alarm_hour < 10 %}0{% endif %}{{ alarm_hour }}:{% if alarm_min_light < 10 %}0{% endif %}{{ alarm_min_light }}
        {% endif %}
        {% endif %}
    robovac_battery:
      unit_of_measurement: '%'
      friendly_name: Batterie
      value_template: '{{ states.vacuum.robovac.attributes.battery_level }}'
      icon_template: '{{ states.vacuum.robovac.attributes.battery_icon }}'
    robovac_status:
      friendly_name: Status
      value_template: '{{ states.vacuum.robovac.attributes.status }}'
    robovac_fanspeed:
      friendly_name: "Saugkraft"
      value_template: '{{ states.vacuum.robovac.attributes.fan_speed }}'