- alias: Sonoff-Tasmota update availability
  id: '111999111'
  trigger:
    platform: time
    at: 09:15:00
  condition:
    condition: template
    value_template: '{{ states.sensor.sonoff_maddox_version.state | replace("v", "")
      != states.sensor.sonoff_3028_version.state[:5] }}'
  action:
  - service: !secret notify_ios
    data_template:
      message: 'Sonoff-Tasmota version {{ states.sensor.sonoff_maddox_version.state
        | replace("v", "") }} is available. Do you wish to upgrade? Changelog: https://is.gd/tasmota'
      data:
        push:
          category: sonoffupdate

- alias: Update Sonoff-Tasmota
  id: '999111999'
  trigger:
    platform: event
    event_type: mobile_app.notification_action_fired
    event_data:
      actionName: UPDATE_SONOFF
  action:
  - service: script.1515151540311

- alias: get tasmota device info
  id: '1500581870914'
  trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: 09:00:00
  action:
  - service: mqtt.publish
    data:
      topic: wemosd1_1/cmnd/Status
      payload: '0'
  - service: mqtt.publish
    data:
      topic: sonoff_3082/cmnd/Status
      payload: '0'
  - service: mqtt.publish
    data:
      topic: sonoff_3463/cmnd/Status
      payload: '0'