- alias: Startup Theme
  id: '20180524211900'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  action:
  - service_template: "{% if states.sun.sun.state == \"above_horizon\" %}\n  shell_command.dark_to_clear_wp\n\
      {% else %}\n  shell_command.clear_to_dark_wp\n{% endif %}\n"
  - service_template: frontend.set_theme
    data_template:
      name: "{% if states.sun.sun.state == \"above_horizon\" %}\n  clear\n{% else\
        \ %}\n  dark_clear\n{% endif %}\n"
  - service: script.lovelace_reload

- alias: Update notifications
  id: '49494'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: !secret notify_ios
    data_template:
      message: Home Assistant {{ states.updater.updater.state }} is now available.

- alias: SSL expiry notification
  id: '1500779870955'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_certificate_expiry
    below: 21
  action:
    service: !secret notify_ios
    data_template:
      message: Warning - SSL certificate expires in {{ states.sensor.ssl_certificate_expiry.state
        }} days and has not been automatically renewed.

- alias: Disk Use Alarm
  id: '7592974'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use
    above: 90
  action:
    service: !secret notify_ios
    data_template:
      message: 'Your harddrive is running out of space: /dev/root: {{ states.sensor.disk_use_percent.state
        }}%'

- alias: Disk Use Alarm sda1
  id: '7592979'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_useperc_sda1
    above: 90
  action:
    service: !secret notify_ios
    data_template:
      message: 'Your harddrive is running out of space: /dev/sda1: {{ states.sensor.disk_useperc_sda1.state
        }}%'

- alias: Disk Use Alarm sda2
  id: '7592978'
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_useperc_sda2
    above: 90
  action:
    service: !secret notify_ios
    data_template:
      message: 'Your harddrive is running out of space: /dev/sda2: {{ states.sensor.disk_useperc_sda2.state
        }}%'

- alias: Log Level
  id: '1500589870955'
  trigger:
    platform: state
    entity_id: input_select.log_level
  condition:
    condition: template
    value_template: '{{ states.input_select.log_level.state != "none" }}'
  action:
    service: logger.set_level
    data_template:
      homeassistant.components: '{{ trigger.to_state.state }}'

- alias: get tasmota device info
  id: '1500581870914'
  trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at: 09:00:00
  action:
  - service: mqtt.publish
    data:
      topic: wemosd1_1/cmnd/Status
      payload: '0'
  - service: mqtt.publish
    data:
      topic: sonoff_3082/cmnd/Status
      payload: '0'
  - service: mqtt.publish
    data:
      topic: sonoff_3463/cmnd/Status
      payload: '0'

- alias: HACS update notifications
  id: '1561215168000'
  trigger:
    platform: numeric_state
    entity_id: sensor.hacs
    above: 5
  action:
    service: !secret notify_ios
    data_template:
      message: 'Custom component updates available: {{ states.sensor.hacs.state }}.'