---
# more sensors

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: history_stats
  name: stats_ratio_athome
  entity_id: !secret person_1
  state: 'home'
  type: ratio
  end: '{{ now() }}'
  duration:
    days: 7
