---
# system sensors

- platform: cert_expiry
  host: !secret ssl_domain

- platform: fail2ban
  scan_interval: 180
  jails:
    - !secret f2b_jail1
    - !secret f2b_jail2
    - !secret f2b_jail3
    - !secret f2b_jail4
    - !secret f2b_jail5
    - !secret f2b_jail6
    - !secret f2b_jail7
