---
# system sensors

- platform: cert_expiry
  host: !secret ssl_domain

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: swap_use_percent
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: fail2ban
  file_path: !secret path_fail2ban
  scan_interval: 180
  jails:
    - !secret f2b_jail1
    - !secret f2b_jail2
    - !secret f2b_jail3
    - !secret f2b_jail4
    - !secret f2b_jail5
    - !secret f2b_jail6
    - !secret f2b_jail7
