sensor:
  - platform: darksky
    api_key: !secret darksky_ak
    forecast:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
    monitored_conditions:
      - icon
      - precip_intensity
      - precip_probability
      - temperature
      - dew_point
      - uv_index
      - wind_speed
      - humidity
      - temperature_min
      - temperature_max
  - platform: season
  - platform: template
    sensors:
      forecast_today:
        friendly_name: "Vorhersage"
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.svg'}}

      forecast_1:
        friendly_name: 'Tomorrow'
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.svg'}}

      forecast_2:
        friendly_name_template: >
            {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
            {{ date | timestamp_custom("%A (%-m/%-d)") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.svg'}}

      forecast_3:
        friendly_name_template: >
            {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
            {{ date | timestamp_custom("%A (%-m/%-d)") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.svg'}}

      forecast_4:
        friendly_name_template: >
            {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
            {{ date | timestamp_custom("%A (%-m/%-d)") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.svg'}}

      forecast_5:
        friendly_name_template: >
            {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
            {{ date | timestamp_custom("%A (%-m/%-d)") }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.svg'}}

      forecast_6:
        friendly_name_template: >
            {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
            {{ date | timestamp_custom("%A (%-m/%-d)") }}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.svg'}}

      forecast_7:
        friendly_name_template: >
            {%- set date = as_timestamp(now()) + (7 * 86400 ) -%}
            {{ date | timestamp_custom("%A (%-m/%-d)") }}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
        entity_picture_template: >-
            {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.svg'}}
