---
# some scripts

wakeup_schlafzimmer:
  alias: 'Wakeup routine: lights and weather'
  sequence:
    - service: scene.turn_on
      data:
        entity_id: scene.deckenspots_nightlight
    - delay:
        seconds: 1
    - service: light.turn_on
      data_template:
        entity_id: light.deckenspots
        brightness: 40
        transition: "{{ states('input_number.wakeup_duration') | multiply(60) | int }}"
magic_mirror_shutdown:
  sequence:
    - service: shell_command.shutdown_rpi
    - wait_template: "{{ is_state('binary_sensor.raspberry_pi', 'off') }}"
      timeout: '00:10:00'
    - delay: 00:01:30
    - service: switch.turn_off
      data:
        entity_id: switch.sonoff_s20_magicmirror_relay
