---
# some scripts

magic_mirror_shutdown:
  sequence:
    - service: shell_command.shutdown_rpi
    - wait_template: "{{ is_state('binary_sensor.raspberry_pi', 'off') }}"
      timeout: '00:10:00'
      continue_on_timeout: false
    - delay: 00:01:30
    - service: switch.turn_off
      entity_id: switch.sonoff_s20_magicmirror_relay

adaptive_lighting_manual_control_reset:
  sequence:
    - service: adaptive_lighting.set_manual_control
      entity_id: switch.adaptive_lighting_main_lights
      data:
        manual_control: false
