---
# sonoff 0528 scripts

'tasmota_upgrade_sonoff_0528':
  sequence:
    - data:
        payload: 'http://thehackbox.org/tasmota/release/tasmota-minimal.bin'
        topic: sonoff_0528/cmnd/OtaUrl
      service: mqtt.publish
    - delay: 00:00:05
    - data:
        payload: '1'
        topic: sonoff_0528/cmnd/Upgrade
      service: mqtt.publish
    - delay: 00:03:00
    - data:
        payload: 'http://thehackbox.org/tasmota/release/tasmota.bin'
        topic: sonoff_0528/cmnd/OtaUrl
      service: mqtt.publish
    - delay: 00:00:05
    - data:
        payload: '1'
        topic: sonoff_0528/cmnd/Upgrade
      service: mqtt.publish
    - delay: 00:03:00
    - service: script.tasmota_fwstatus_sonoff_0528
'tasmota_restart_sonoff_0528':
  sequence:
    - data:
        payload: '1'
        topic: sonoff_0528/cmnd/Restart
      service: mqtt.publish
'tasmota_status_sonoff_0528':
  sequence:
    - data:
        payload: '0'
        topic: sonoff_0528/cmnd/Status
      service: mqtt.publish
'tasmota_reset_sonoff_0528':
  sequence:
    - data:
        payload: '1'
        topic: sonoff_0528/cmnd/Reset
      service: mqtt.publish
'tasmota_fwstatus_sonoff_0528':
  sequence:
    - data:
        payload: '2'
        topic: sonoff_0528/cmnd/Status
      service: mqtt.publish
