# This is a basic workflow to help you get started with Actions

name: Home Assistant Config Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 12 * * *

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v1.0.0
        with:
          config_file: .yamllint.yml
  test-config:
    runs-on: ubuntu-latest
    needs: lint-files
    steps:
      - uses: actions/checkout@v2
      - name: Home Assistant Configuration dev check
        uses: ludeeus/action-ha-config-check@0.0.1
        env:
          ACTION_VERSION: DEV
          ACTION_ALLOW_FAIL: True
      - name: Home Assistant Configuration rc check
        uses: ludeeus/action-ha-config-check@0.0.1
        env:
          ACTION_VERSION: RC
      - name: Home Assistant Configuration stable check
        uses: ludeeus/action-ha-config-check@0.0.1
        env:
          ACTION_VERSION: STABLE
