---
name: hass-config-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 12 * * *

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml

  home-assistant:
    name: Home Assistant Core Configuration Check
    runs-on: ubuntu-latest
    needs: yaml-lint
    strategy:
      matrix:
        version: ["stable", "beta"]
    steps:
      - uses: actions/checkout@v3
      - name: Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "./config"
          secrets: .not_secrets.yaml
          version: "${{ matrix.version }}"
