# This is a basic workflow to help you get started with Actions

name: hass-config-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 12 * * *

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v1.0.0
        with:
          config_file: .yamllint.yml

  hass-stable:
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - uses: actions/checkout@v2
      - name: create secrets file
        run: mv .not_secrets.yaml config/secrets.yaml
      - name: create files
        run: touch config/sshkey && touch config/fail2ban.log && touch config/diskinfo.txt && touch config/diskinfo1.txt
      - name: fix external-dirs-whitelist
        run: awk '$1 == "homeassistant:"{t=1} t==1 && $1 == "whitelist_external_dirs:"{t++; next} t==2 && /:[[:blank:]]*$/{t=0} t != 2' config/configuration.yaml > config/configuration.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --config ./config/ --script check_config --info all

  hass-rc:
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - uses: actions/checkout@v2
      - name: create secrets file
        run: mv .not_secrets.yaml config/secrets.yaml
      - name: create files
        run: touch config/sshkey && touch config/fail2ban.log && touch config/diskinfo.txt && touch config/diskinfo1.txt
      - name: fix external-dirs-whitelist
        run: awk '$1 == "homeassistant:"{t=1} t==1 && $1 == "whitelist_external_dirs:"{t++; next} t==2 && /:[[:blank:]]*$/{t=0} t != 2' config/configuration.yaml > config/configuration.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:rc"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:rc"
        with:
          args: |
            python -m homeassistant --config ./config/ --script check_config --info all

  hass-dev:
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - uses: actions/checkout@v2
      - name: create secrets file
        run: mv .not_secrets.yaml config/secrets.yaml
      - name: create files
        run: touch config/sshkey && touch config/fail2ban.log && touch config/diskinfo.txt && touch config/diskinfo1.txt
      - name: fix external-dirs-whitelist
        run: awk '$1 == "homeassistant:"{t=1} t==1 && $1 == "whitelist_external_dirs:"{t++; next} t==2 && /:[[:blank:]]*$/{t=0} t != 2' config/configuration.yaml > config/configuration.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: |
            python -m homeassistant --config ./config/ --script check_config --info all
